import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const START_ID = 439;
const END_ID = 2188;
const EXPECTED_COUNT = END_ID - START_ID + 1;
const BATCH_SIZE = 100;

/**
 * 1.750 địa chỉ tương ứng với Tenant ID 439 -> 2188.
 *
 * Quy tắc ánh xạ:
 * - Tenant 439  -> TENANT_ADDRESSES[0]
 * - Tenant 440  -> TENANT_ADDRESSES[1]
 * - ...
 * - Tenant 2188 -> TENANT_ADDRESSES[1749]
 */
export const TENANT_ADDRESSES = [
  "Phường An Bình, Thành phố Hà Nội",
  "Phường An Hòa, Thành phố Hà Nội",
  "Phường An Phú, Thành phố Hà Nội",
  "Phường An Lạc, Thành phố Hà Nội",
  "Phường An Thịnh, Thành phố Hà Nội",
  "Phường An Thành, Thành phố Hà Nội",
  "Phường An Sơn, Thành phố Hà Nội",
  "Phường An Khánh, Thành phố Hà Nội",
  "Phường Bình An, Thành phố Hà Nội",
  "Phường Bình Minh, Thành phố Hà Nội",
  "Phường Bình Phú, Thành phố Hà Nội",
  "Phường Bình Hòa, Thành phố Hà Nội",
  "Phường Bình Thành, Thành phố Hà Nội",
  "Phường Bình Sơn, Thành phố Hà Nội",
  "Phường Bình Lộc, Thành phố Hà Nội",
  "Phường Bình Thịnh, Thành phố Hà Nội",
  "Phường Hòa Bình, Thành phố Hà Nội",
  "Phường Hòa Phú, Thành phố Hà Nội",
  "Phường Hòa An, Thành phố Hà Nội",
  "Phường Hòa Thành, Thành phố Hà Nội",
  "Phường Hòa Sơn, Thành phố Hà Nội",
  "Phường Hòa Lộc, Thành phố Hà Nội",
  "Phường Hòa Thịnh, Thành phố Hà Nội",
  "Phường Hòa Minh, Thành phố Hà Nội",
  "Phường Phú An, Thành phố Hà Nội",
  "Phường Phú Bình, Thành phố Hà Nội",
  "Phường Phú Hòa, Thành phố Hà Nội",
  "Phường Phú Lộc, Thành phố Hà Nội",
  "Phường Phú Mỹ, Thành phố Hà Nội",
  "Phường Phú Sơn, Thành phố Hà Nội",
  "Phường Phú Thành, Thành phố Hà Nội",
  "Phường Phú Thịnh, Thành phố Hà Nội",
  "Phường Tân An, Thành phố Hà Nội",
  "Phường Tân Bình, Thành phố Hà Nội",
  "Phường Tân Hòa, Thành phố Hà Nội",
  "Phường Tân Phú, Thành phố Hà Nội",
  "Phường Tân Lập, Thành phố Hà Nội",
  "Phường Tân Thành, Thành phố Hà Nội",
  "Phường Tân Tiến, Thành phố Hà Nội",
  "Phường Tân Hưng, Thành phố Hà Nội",
  "Phường Tân Long, Thành phố Hà Nội",
  "Phường Tân Phong, Thành phố Hà Nội",
  "Phường Tân Thịnh, Thành phố Hà Nội",
  "Phường Tân Xuân, Thành phố Hà Nội",
  "Phường Tân Sơn, Thành phố Hà Nội",
  "Phường Tân Thành, Thành phố Hải Phòng",
  "Phường Tân Tiến, Thành phố Hải Phòng",
  "Phường Tân Hưng, Thành phố Hải Phòng",
  "Phường Tân Long, Thành phố Hải Phòng",
  "Phường Tân Phong, Thành phố Hải Phòng",
  "Phường Tân Thịnh, Thành phố Hải Phòng",
  "Phường Tân Xuân, Thành phố Hải Phòng",
  "Phường Tân Sơn, Thành phố Hải Phòng",
  "Phường Tân Lộc, Thành phố Hải Phòng",
  "Phường Tân Mỹ, Thành phố Hải Phòng",
  "Phường Tân Minh, Thành phố Hải Phòng",
  "Phường Minh Tân, Thành phố Hải Phòng",
  "Phường Minh Phú, Thành phố Hải Phòng",
  "Phường Minh Hòa, Thành phố Hải Phòng",
  "Phường Minh Sơn, Thành phố Hải Phòng",
  "Phường Minh Đức, Thành phố Hải Phòng",
  "Phường Minh Thành, Thành phố Hải Phòng",
  "Phường Minh An, Thành phố Hải Phòng",
  "Phường Minh Lộc, Thành phố Hải Phòng",
  "Phường Đông Hòa, Thành phố Hải Phòng",
  "Phường Đông Phú, Thành phố Hải Phòng",
  "Phường Đông Sơn, Thành phố Hải Phòng",
  "Phường Đông Thành, Thành phố Hải Phòng",
  "Phường Đông An, Thành phố Hải Phòng",
  "Phường Đông Lộc, Thành phố Hải Phòng",
  "Phường Đông Thịnh, Thành phố Hải Phòng",
  "Phường Đông Minh, Thành phố Hải Phòng",
  "Phường Tây Sơn, Thành phố Hải Phòng",
  "Phường Tây Phú, Thành phố Hải Phòng",
  "Phường Tây Hòa, Thành phố Hải Phòng",
  "Phường Tây An, Thành phố Hải Phòng",
  "Phường Tây Thành, Thành phố Hải Phòng",
  "Phường Tây Lộc, Thành phố Hải Phòng",
  "Phường Tây Thịnh, Thành phố Hải Phòng",
  "Phường Tây Minh, Thành phố Hải Phòng",
  "Phường Nam Sơn, Thành phố Hải Phòng",
  "Phường Nam Phú, Thành phố Hải Phòng",
  "Phường Nam Hòa, Thành phố Hải Phòng",
  "Phường Nam An, Thành phố Hải Phòng",
  "Phường Nam Thành, Thành phố Hải Phòng",
  "Phường Nam Hòa, Thành phố Huế",
  "Phường Nam An, Thành phố Huế",
  "Phường Nam Thành, Thành phố Huế",
  "Phường Nam Lộc, Thành phố Huế",
  "Phường Nam Thịnh, Thành phố Huế",
  "Phường Nam Bình, Thành phố Huế",
  "Phường Bắc Sơn, Thành phố Huế",
  "Phường Bắc Phú, Thành phố Huế",
  "Phường Bắc Hòa, Thành phố Huế",
  "Phường Bắc An, Thành phố Huế",
  "Phường Bắc Thành, Thành phố Huế",
  "Phường Bắc Lộc, Thành phố Huế",
  "Phường Bắc Thịnh, Thành phố Huế",
  "Phường Bắc Bình, Thành phố Huế",
  "Phường Xuân Hòa, Thành phố Huế",
  "Phường Xuân Phú, Thành phố Huế",
  "Phường Xuân Lộc, Thành phố Huế",
  "Phường Xuân Sơn, Thành phố Huế",
  "Phường Xuân Thành, Thành phố Huế",
  "Phường Xuân Thịnh, Thành phố Huế",
  "Phường Xuân An, Thành phố Huế",
  "Phường Đại Minh, Thành phố Đà Nẵng",
  "Phường Long An, Thành phố Đà Nẵng",
  "Phường Long Bình, Thành phố Đà Nẵng",
  "Phường Long Phú, Thành phố Đà Nẵng",
  "Phường Long Hòa, Thành phố Đà Nẵng",
  "Phường Long Thành, Thành phố Đà Nẵng",
  "Phường Long Sơn, Thành phố Đà Nẵng",
  "Phường Long Lộc, Thành phố Đà Nẵng",
  "Phường Long Thịnh, Thành phố Đà Nẵng",
  "Phường Thành Công, Thành phố Đà Nẵng",
  "Phường Thành An, Thành phố Đà Nẵng",
  "Phường Thành Bình, Thành phố Đà Nẵng",
  "Phường Thành Phú, Thành phố Đà Nẵng",
  "Phường Thành Hòa, Thành phố Đà Nẵng",
  "Phường Thành Lộc, Thành phố Đà Nẵng",
  "Phường Thành Sơn, Thành phố Đà Nẵng",
  "Phường Thành Minh, Thành phố Đà Nẵng",
  "Phường Hưng Phú, Thành phố Đà Nẵng",
  "Phường Hưng Thịnh, Thành phố Đà Nẵng",
  "Phường Hưng Hòa, Thành phố Đà Nẵng",
  "Phường Hưng Thành, Thành phố Đà Nẵng",
  "Phường Hưng An, Thành phố Đà Nẵng",
  "Phường Hưng Bình, Thành phố Đà Nẵng",
  "Phường Yên Sơn, Thành phố Cần Thơ",
  "Phường Yên An, Thành phố Cần Thơ",
  "Phường Yên Lộc, Thành phố Cần Thơ",
  "Phường Yên Thịnh, Thành phố Cần Thơ",
  "Phường Quang Trung, Thành phố Cần Thơ",
  "Phường Quang Minh, Thành phố Cần Thơ",
  "Phường Quang Phú, Thành phố Cần Thơ",
  "Phường Quang Hòa, Thành phố Cần Thơ",
  "Phường Quang An, Thành phố Cần Thơ",
  "Phường Quang Thành, Thành phố Cần Thơ",
  "Phường Quang Sơn, Thành phố Cần Thơ",
  "Phường Quang Lộc, Thành phố Cần Thơ",
  "Phường Đức Hòa, Thành phố Cần Thơ",
  "Phường Đức Phú, Thành phố Cần Thơ",
  "Phường Đức Thành, Thành phố Cần Thơ",
  "Phường Đức Thịnh, Thành phố Cần Thơ",
  "Phường Đức An, Thành phố Cần Thơ",
  "Phường Đức Bình, Thành phố Cần Thơ",
  "Phường Đức Sơn, Thành phố Cần Thơ",
  "Phường Đức Lộc, Thành phố Cần Thơ",
  "Phường Vĩnh An, Thành phố Cần Thơ",
  "Phường Vĩnh Bình, Thành phố Cần Thơ",
  "Phường Vĩnh Phú, Thành phố Cần Thơ",
  "Phường Vĩnh Hòa, Thành phố Cần Thơ",
  "Phường Vĩnh Thành, Thành phố Cần Thơ",
  "Phường Vĩnh Sơn, Thành phố Cần Thơ",
  "Phường Vĩnh Lộc, Thành phố Cần Thơ",
  "Phường Vĩnh Thịnh, Thành phố Cần Thơ",
  "Phường Lộc An, Thành phố Cần Thơ",
  "Phường Lộc Bình, Thành phố Cần Thơ",
  "Phường Lộc Phú, Thành phố Cần Thơ",
  "Xã Bình Hòa, Tỉnh Cao Bằng",
  "Xã Bình Thành, Tỉnh Cao Bằng",
  "Xã Bình Sơn, Tỉnh Cao Bằng",
  "Xã Bình Lộc, Tỉnh Cao Bằng",
  "Xã Bình Thịnh, Tỉnh Cao Bằng",
  "Xã Hòa Bình, Tỉnh Cao Bằng",
  "Xã Hòa Phú, Tỉnh Cao Bằng",
  "Xã Hòa An, Tỉnh Cao Bằng",
  "Xã Hòa Thành, Tỉnh Cao Bằng",
  "Xã Hòa Sơn, Tỉnh Cao Bằng",
  "Xã Hòa Lộc, Tỉnh Cao Bằng",
  "Xã Hòa Thịnh, Tỉnh Cao Bằng",
  "Xã Hòa Minh, Tỉnh Cao Bằng",
  "Xã Phú An, Tỉnh Cao Bằng",
  "Xã Phú Bình, Tỉnh Cao Bằng",
  "Xã Phú Hòa, Tỉnh Cao Bằng",
  "Xã Phú Lộc, Tỉnh Cao Bằng",
  "Xã Phú Mỹ, Tỉnh Cao Bằng",
  "Xã Phú Sơn, Tỉnh Cao Bằng",
  "Xã Phú Thành, Tỉnh Cao Bằng",
  "Xã Phú Thịnh, Tỉnh Cao Bằng",
  "Xã Tân An, Tỉnh Cao Bằng",
  "Xã Tân Bình, Tỉnh Cao Bằng",
  "Xã Tân Hòa, Tỉnh Cao Bằng",
  "Xã Tân Phú, Tỉnh Cao Bằng",
  "Xã Tân Lập, Tỉnh Cao Bằng",
  "Xã Tân Thành, Tỉnh Cao Bằng",
  "Xã Tân Tiến, Tỉnh Cao Bằng",
  "Xã Tân Hưng, Tỉnh Cao Bằng",
  "Xã Tân Long, Tỉnh Cao Bằng",
  "Xã Tân Phong, Tỉnh Cao Bằng",
  "Xã Tân Thịnh, Tỉnh Cao Bằng",
  "Xã Tân Xuân, Tỉnh Cao Bằng",
  "Xã Tân Sơn, Tỉnh Cao Bằng",
  "Xã Tân Lộc, Tỉnh Cao Bằng",
  "Xã Tân Mỹ, Tỉnh Cao Bằng",
  "Xã Tân Minh, Tỉnh Cao Bằng",
  "Xã Minh Tân, Tỉnh Cao Bằng",
  "Xã Minh Phú, Tỉnh Cao Bằng",
  "Xã Minh Hòa, Tỉnh Cao Bằng",
  "Xã Minh Sơn, Tỉnh Cao Bằng",
  "Xã Minh Đức, Tỉnh Cao Bằng",
  "Xã Minh Thành, Tỉnh Cao Bằng",
  "Xã Minh An, Tỉnh Cao Bằng",
  "Xã Minh Lộc, Tỉnh Cao Bằng",
  "Xã Đông Hòa, Tỉnh Cao Bằng",
  "Xã Đông Phú, Tỉnh Cao Bằng",
  "Xã Đông Sơn, Tỉnh Cao Bằng",
  "Xã Đông Thành, Tỉnh Cao Bằng",
  "Xã Đông An, Tỉnh Cao Bằng",
  "Xã Đông Lộc, Tỉnh Cao Bằng",
  "Xã Đông Thịnh, Tỉnh Cao Bằng",
  "Xã Đông Minh, Tỉnh Cao Bằng",
  "Xã Tây Sơn, Tỉnh Cao Bằng",
  "Xã Tây Phú, Tỉnh Cao Bằng",
  "Xã Tây Hòa, Tỉnh Cao Bằng",
  "Xã Tây An, Tỉnh Cao Bằng",
  "Xã Tân Long, Tỉnh Tuyên Quang",
  "Xã Tân Phong, Tỉnh Tuyên Quang",
  "Xã Tân Thịnh, Tỉnh Tuyên Quang",
  "Xã Tân Xuân, Tỉnh Tuyên Quang",
  "Xã Tân Sơn, Tỉnh Tuyên Quang",
  "Xã Tân Lộc, Tỉnh Tuyên Quang",
  "Xã Tân Mỹ, Tỉnh Tuyên Quang",
  "Xã Tân Minh, Tỉnh Tuyên Quang",
  "Xã Minh Tân, Tỉnh Tuyên Quang",
  "Xã Minh Phú, Tỉnh Tuyên Quang",
  "Xã Minh Hòa, Tỉnh Tuyên Quang",
  "Xã Minh Sơn, Tỉnh Tuyên Quang",
  "Xã Minh Đức, Tỉnh Tuyên Quang",
  "Xã Minh Thành, Tỉnh Tuyên Quang",
  "Xã Minh An, Tỉnh Tuyên Quang",
  "Xã Minh Lộc, Tỉnh Tuyên Quang",
  "Xã Đông Hòa, Tỉnh Tuyên Quang",
  "Xã Đông Phú, Tỉnh Tuyên Quang",
  "Xã Đông Sơn, Tỉnh Tuyên Quang",
  "Xã Đông Thành, Tỉnh Tuyên Quang",
  "Xã Đông An, Tỉnh Tuyên Quang",
  "Xã Đông Lộc, Tỉnh Tuyên Quang",
  "Xã Đông Thịnh, Tỉnh Tuyên Quang",
  "Xã Đông Minh, Tỉnh Tuyên Quang",
  "Xã Tây Sơn, Tỉnh Tuyên Quang",
  "Xã Tây Phú, Tỉnh Tuyên Quang",
  "Xã Tây Hòa, Tỉnh Tuyên Quang",
  "Xã Tây An, Tỉnh Tuyên Quang",
  "Xã Tây Thành, Tỉnh Tuyên Quang",
  "Xã Tây Lộc, Tỉnh Tuyên Quang",
  "Xã Tây Thịnh, Tỉnh Tuyên Quang",
  "Xã Tây Minh, Tỉnh Tuyên Quang",
  "Xã Nam Sơn, Tỉnh Tuyên Quang",
  "Xã Nam Phú, Tỉnh Tuyên Quang",
  "Xã Nam Hòa, Tỉnh Tuyên Quang",
  "Xã Nam An, Tỉnh Tuyên Quang",
  "Xã Nam Thành, Tỉnh Tuyên Quang",
  "Xã Nam Lộc, Tỉnh Tuyên Quang",
  "Xã Nam Thịnh, Tỉnh Tuyên Quang",
  "Xã Nam Bình, Tỉnh Tuyên Quang",
  "Xã Bắc Sơn, Tỉnh Tuyên Quang",
  "Xã Bắc Phú, Tỉnh Tuyên Quang",
  "Xã Bắc Hòa, Tỉnh Tuyên Quang",
  "Xã Bắc An, Tỉnh Tuyên Quang",
  "Xã Bắc Thành, Tỉnh Tuyên Quang",
  "Xã Bắc Lộc, Tỉnh Tuyên Quang",
  "Xã Bắc Thịnh, Tỉnh Tuyên Quang",
  "Xã Bắc Bình, Tỉnh Tuyên Quang",
  "Xã Xuân Hòa, Tỉnh Tuyên Quang",
  "Xã Xuân Phú, Tỉnh Tuyên Quang",
  "Xã Xuân Lộc, Tỉnh Tuyên Quang",
  "Xã Xuân Sơn, Tỉnh Tuyên Quang",
  "Xã Xuân Thành, Tỉnh Tuyên Quang",
  "Xã Xuân Thịnh, Tỉnh Tuyên Quang",
  "Xã Xuân An, Tỉnh Tuyên Quang",
  "Xã Xuân Bình, Tỉnh Tuyên Quang",
  "Xã Trung Sơn, Tỉnh Tuyên Quang",
  "Xã Tây Lộc, Tỉnh Điện Biên",
  "Xã Tây Thịnh, Tỉnh Điện Biên",
  "Xã Tây Minh, Tỉnh Điện Biên",
  "Xã Nam Sơn, Tỉnh Điện Biên",
  "Xã Nam Phú, Tỉnh Điện Biên",
  "Xã Nam Hòa, Tỉnh Điện Biên",
  "Xã Nam An, Tỉnh Điện Biên",
  "Xã Nam Thành, Tỉnh Điện Biên",
  "Xã Nam Lộc, Tỉnh Điện Biên",
  "Xã Nam Thịnh, Tỉnh Điện Biên",
  "Xã Nam Bình, Tỉnh Điện Biên",
  "Xã Bắc Sơn, Tỉnh Điện Biên",
  "Xã Bắc Phú, Tỉnh Điện Biên",
  "Xã Bắc Hòa, Tỉnh Điện Biên",
  "Xã Bắc An, Tỉnh Điện Biên",
  "Xã Bắc Thành, Tỉnh Điện Biên",
  "Xã Bắc Lộc, Tỉnh Điện Biên",
  "Xã Bắc Thịnh, Tỉnh Điện Biên",
  "Xã Bắc Bình, Tỉnh Điện Biên",
  "Xã Xuân Hòa, Tỉnh Điện Biên",
  "Xã Xuân Phú, Tỉnh Điện Biên",
  "Xã Xuân Lộc, Tỉnh Điện Biên",
  "Xã Xuân Sơn, Tỉnh Điện Biên",
  "Xã Xuân Thành, Tỉnh Điện Biên",
  "Xã Xuân Thịnh, Tỉnh Điện Biên",
  "Xã Xuân An, Tỉnh Điện Biên",
  "Xã Xuân Bình, Tỉnh Điện Biên",
  "Xã Trung Sơn, Tỉnh Điện Biên",
  "Xã Trung Hòa, Tỉnh Điện Biên",
  "Xã Trung Thành, Tỉnh Điện Biên",
  "Xã Trung An, Tỉnh Điện Biên",
  "Xã Trung Phú, Tỉnh Điện Biên",
  "Xã Trung Lộc, Tỉnh Điện Biên",
  "Xã Trung Thịnh, Tỉnh Điện Biên",
  "Xã Trung Bình, Tỉnh Điện Biên",
  "Xã Đại An, Tỉnh Điện Biên",
  "Xã Đại Phú, Tỉnh Điện Biên",
  "Xã Đại Hòa, Tỉnh Điện Biên",
  "Xã Đại Sơn, Tỉnh Điện Biên",
  "Xã Đại Thành, Tỉnh Điện Biên",
  "Xã Đại Lộc, Tỉnh Điện Biên",
  "Xã Đại Bình, Tỉnh Điện Biên",
  "Xã Đại Minh, Tỉnh Điện Biên",
  "Xã Long An, Tỉnh Điện Biên",
  "Xã Long Bình, Tỉnh Điện Biên",
  "Xã Long Phú, Tỉnh Điện Biên",
  "Xã Long Hòa, Tỉnh Điện Biên",
  "Xã Long Thành, Tỉnh Điện Biên",
  "Xã Long Sơn, Tỉnh Điện Biên",
  "Xã Long Lộc, Tỉnh Điện Biên",
  "Xã Long Thịnh, Tỉnh Điện Biên",
  "Xã Thành Công, Tỉnh Điện Biên",
  "Xã Thành An, Tỉnh Điện Biên",
  "Xã Thành Bình, Tỉnh Điện Biên",
  "Xã Thành Phú, Tỉnh Điện Biên",
  "Xã Thành Hòa, Tỉnh Điện Biên",
  "Xã Thành Lộc, Tỉnh Điện Biên",
  "Xã Trung Thành, Tỉnh Lai Châu",
  "Xã Trung An, Tỉnh Lai Châu",
  "Xã Trung Phú, Tỉnh Lai Châu",
  "Xã Trung Lộc, Tỉnh Lai Châu",
  "Xã Trung Thịnh, Tỉnh Lai Châu",
  "Xã Trung Bình, Tỉnh Lai Châu",
  "Xã Đại An, Tỉnh Lai Châu",
  "Xã Đại Phú, Tỉnh Lai Châu",
  "Xã Đại Hòa, Tỉnh Lai Châu",
  "Xã Đại Sơn, Tỉnh Lai Châu",
  "Xã Đại Thành, Tỉnh Lai Châu",
  "Xã Đại Lộc, Tỉnh Lai Châu",
  "Xã Đại Bình, Tỉnh Lai Châu",
  "Xã Đại Minh, Tỉnh Lai Châu",
  "Xã Long An, Tỉnh Lai Châu",
  "Xã Long Bình, Tỉnh Lai Châu",
  "Xã Long Phú, Tỉnh Lai Châu",
  "Xã Long Hòa, Tỉnh Lai Châu",
  "Xã Long Thành, Tỉnh Lai Châu",
  "Xã Long Sơn, Tỉnh Lai Châu",
  "Xã Long Lộc, Tỉnh Lai Châu",
  "Xã Long Thịnh, Tỉnh Lai Châu",
  "Xã Thành Công, Tỉnh Lai Châu",
  "Xã Thành An, Tỉnh Lai Châu",
  "Xã Thành Bình, Tỉnh Lai Châu",
  "Xã Thành Phú, Tỉnh Lai Châu",
  "Xã Thành Hòa, Tỉnh Lai Châu",
  "Xã Thành Lộc, Tỉnh Lai Châu",
  "Xã Thành Sơn, Tỉnh Lai Châu",
  "Xã Thành Minh, Tỉnh Lai Châu",
  "Xã Hưng Phú, Tỉnh Lai Châu",
  "Xã Hưng Thịnh, Tỉnh Lai Châu",
  "Xã Hưng Hòa, Tỉnh Lai Châu",
  "Xã Hưng Thành, Tỉnh Lai Châu",
  "Xã Hưng An, Tỉnh Lai Châu",
  "Xã Hưng Bình, Tỉnh Lai Châu",
  "Xã Hưng Lộc, Tỉnh Lai Châu",
  "Xã Hưng Sơn, Tỉnh Lai Châu",
  "Xã Thịnh An, Tỉnh Lai Châu",
  "Xã Thịnh Phú, Tỉnh Lai Châu",
  "Xã Thịnh Hòa, Tỉnh Lai Châu",
  "Xã Thịnh Thành, Tỉnh Lai Châu",
  "Xã Thịnh Bình, Tỉnh Lai Châu",
  "Xã Thịnh Sơn, Tỉnh Lai Châu",
  "Xã Thịnh Lộc, Tỉnh Lai Châu",
  "Xã Thịnh Minh, Tỉnh Lai Châu",
  "Xã Yên Bình, Tỉnh Lai Châu",
  "Xã Yên Phú, Tỉnh Lai Châu",
  "Xã Yên Hòa, Tỉnh Lai Châu",
  "Xã Yên Thành, Tỉnh Lai Châu",
  "Xã Yên Sơn, Tỉnh Lai Châu",
  "Xã Yên An, Tỉnh Lai Châu",
  "Xã Yên Lộc, Tỉnh Lai Châu",
  "Xã Yên Thịnh, Tỉnh Lai Châu",
  "Xã Quang Trung, Tỉnh Lai Châu",
  "Xã Quang Minh, Tỉnh Lai Châu",
  "Xã Quang Phú, Tỉnh Lai Châu",
  "Xã Thành Minh, Tỉnh Sơn La",
  "Xã Hưng Phú, Tỉnh Sơn La",
  "Xã Hưng Thịnh, Tỉnh Sơn La",
  "Xã Hưng Hòa, Tỉnh Sơn La",
  "Xã Hưng Thành, Tỉnh Sơn La",
  "Xã Hưng An, Tỉnh Sơn La",
  "Xã Hưng Bình, Tỉnh Sơn La",
  "Xã Hưng Lộc, Tỉnh Sơn La",
  "Xã Hưng Sơn, Tỉnh Sơn La",
  "Xã Thịnh An, Tỉnh Sơn La",
  "Xã Thịnh Phú, Tỉnh Sơn La",
  "Xã Thịnh Hòa, Tỉnh Sơn La",
  "Xã Thịnh Thành, Tỉnh Sơn La",
  "Xã Thịnh Bình, Tỉnh Sơn La",
  "Xã Thịnh Sơn, Tỉnh Sơn La",
  "Xã Thịnh Lộc, Tỉnh Sơn La",
  "Xã Thịnh Minh, Tỉnh Sơn La",
  "Xã Yên Bình, Tỉnh Sơn La",
  "Xã Yên Phú, Tỉnh Sơn La",
  "Xã Yên Hòa, Tỉnh Sơn La",
  "Xã Yên Thành, Tỉnh Sơn La",
  "Xã Yên Sơn, Tỉnh Sơn La",
  "Xã Yên An, Tỉnh Sơn La",
  "Xã Yên Lộc, Tỉnh Sơn La",
  "Xã Yên Thịnh, Tỉnh Sơn La",
  "Xã Quang Trung, Tỉnh Sơn La",
  "Xã Quang Minh, Tỉnh Sơn La",
  "Xã Quang Phú, Tỉnh Sơn La",
  "Xã Quang Hòa, Tỉnh Sơn La",
  "Xã Quang An, Tỉnh Sơn La",
  "Xã Quang Thành, Tỉnh Sơn La",
  "Xã Quang Sơn, Tỉnh Sơn La",
  "Xã Quang Lộc, Tỉnh Sơn La",
  "Xã Đức Hòa, Tỉnh Sơn La",
  "Xã Đức Phú, Tỉnh Sơn La",
  "Xã Đức Thành, Tỉnh Sơn La",
  "Xã Đức Thịnh, Tỉnh Sơn La",
  "Xã Đức An, Tỉnh Sơn La",
  "Xã Đức Bình, Tỉnh Sơn La",
  "Xã Đức Sơn, Tỉnh Sơn La",
  "Xã Đức Lộc, Tỉnh Sơn La",
  "Xã Vĩnh An, Tỉnh Sơn La",
  "Xã Vĩnh Bình, Tỉnh Sơn La",
  "Xã Vĩnh Phú, Tỉnh Sơn La",
  "Xã Vĩnh Hòa, Tỉnh Sơn La",
  "Xã Vĩnh Thành, Tỉnh Sơn La",
  "Xã Vĩnh Sơn, Tỉnh Sơn La",
  "Xã Vĩnh Lộc, Tỉnh Sơn La",
  "Xã Vĩnh Thịnh, Tỉnh Sơn La",
  "Xã Lộc An, Tỉnh Sơn La",
  "Xã Lộc Bình, Tỉnh Sơn La",
  "Xã Lộc Phú, Tỉnh Sơn La",
  "Xã Lộc Hòa, Tỉnh Sơn La",
  "Xã Lộc Thành, Tỉnh Sơn La",
  "Xã Lộc Sơn, Tỉnh Sơn La",
  "Xã Lộc Thịnh, Tỉnh Sơn La",
  "Xã Lộc Minh, Tỉnh Sơn La",
  "Xã Quang An, Tỉnh Lào Cai",
  "Xã Quang Thành, Tỉnh Lào Cai",
  "Xã Quang Sơn, Tỉnh Lào Cai",
  "Xã Quang Lộc, Tỉnh Lào Cai",
  "Xã Đức Hòa, Tỉnh Lào Cai",
  "Xã Đức Phú, Tỉnh Lào Cai",
  "Xã Đức Thành, Tỉnh Lào Cai",
  "Xã Đức Thịnh, Tỉnh Lào Cai",
  "Xã Đức An, Tỉnh Lào Cai",
  "Xã Đức Bình, Tỉnh Lào Cai",
  "Xã Đức Sơn, Tỉnh Lào Cai",
  "Xã Đức Lộc, Tỉnh Lào Cai",
  "Xã Vĩnh An, Tỉnh Lào Cai",
  "Xã Vĩnh Bình, Tỉnh Lào Cai",
  "Xã Vĩnh Phú, Tỉnh Lào Cai",
  "Xã Vĩnh Hòa, Tỉnh Lào Cai",
  "Xã Vĩnh Thành, Tỉnh Lào Cai",
  "Xã Vĩnh Sơn, Tỉnh Lào Cai",
  "Xã Vĩnh Lộc, Tỉnh Lào Cai",
  "Xã Vĩnh Thịnh, Tỉnh Lào Cai",
  "Xã Lộc An, Tỉnh Lào Cai",
  "Xã Lộc Bình, Tỉnh Lào Cai",
  "Xã Lộc Phú, Tỉnh Lào Cai",
  "Xã Lộc Hòa, Tỉnh Lào Cai",
  "Xã Lộc Thành, Tỉnh Lào Cai",
  "Xã Lộc Sơn, Tỉnh Lào Cai",
  "Xã Lộc Thịnh, Tỉnh Lào Cai",
  "Xã Lộc Minh, Tỉnh Lào Cai",
  "Xã Mỹ An, Tỉnh Lào Cai",
  "Xã Mỹ Bình, Tỉnh Lào Cai",
  "Xã Mỹ Phú, Tỉnh Lào Cai",
  "Xã Mỹ Hòa, Tỉnh Lào Cai",
  "Xã Mỹ Thành, Tỉnh Lào Cai",
  "Xã Mỹ Sơn, Tỉnh Lào Cai",
  "Xã Mỹ Lộc, Tỉnh Lào Cai",
  "Xã Mỹ Thịnh, Tỉnh Lào Cai",
  "Xã Kim Sơn, Tỉnh Lào Cai",
  "Xã Kim Phú, Tỉnh Lào Cai",
  "Xã Kim Thành, Tỉnh Lào Cai",
  "Xã Kim An, Tỉnh Lào Cai",
  "Xã Kim Bình, Tỉnh Lào Cai",
  "Xã Kim Hòa, Tỉnh Lào Cai",
  "Xã Kim Lộc, Tỉnh Lào Cai",
  "Xã Kim Thịnh, Tỉnh Lào Cai",
  "Xã Thanh Bình, Tỉnh Lào Cai",
  "Xã Thanh Phú, Tỉnh Lào Cai",
  "Xã Thanh Hòa, Tỉnh Lào Cai",
  "Xã Thanh Sơn, Tỉnh Lào Cai",
  "Xã Thanh Thành, Tỉnh Lào Cai",
  "Xã Thanh An, Tỉnh Lào Cai",
  "Xã Thanh Lộc, Tỉnh Lào Cai",
  "Xã Thanh Thịnh, Tỉnh Lào Cai",
  "Xã An Bình, Tỉnh Lào Cai",
  "Xã An Hòa, Tỉnh Lào Cai",
  "Xã An Phú, Tỉnh Lào Cai",
  "Xã An Lạc, Tỉnh Lào Cai",
  "Xã An Thịnh, Tỉnh Lào Cai",
  "Xã Mỹ Bình, Tỉnh Thái Nguyên",
  "Xã Mỹ Phú, Tỉnh Thái Nguyên",
  "Xã Mỹ Hòa, Tỉnh Thái Nguyên",
  "Xã Mỹ Thành, Tỉnh Thái Nguyên",
  "Xã Mỹ Sơn, Tỉnh Thái Nguyên",
  "Xã Mỹ Lộc, Tỉnh Thái Nguyên",
  "Xã Mỹ Thịnh, Tỉnh Thái Nguyên",
  "Xã Kim Sơn, Tỉnh Thái Nguyên",
  "Xã Kim Phú, Tỉnh Thái Nguyên",
  "Xã Kim Thành, Tỉnh Thái Nguyên",
  "Xã Kim An, Tỉnh Thái Nguyên",
  "Xã Kim Bình, Tỉnh Thái Nguyên",
  "Xã Kim Hòa, Tỉnh Thái Nguyên",
  "Xã Kim Lộc, Tỉnh Thái Nguyên",
  "Xã Kim Thịnh, Tỉnh Thái Nguyên",
  "Xã Thanh Bình, Tỉnh Thái Nguyên",
  "Xã Thanh Phú, Tỉnh Thái Nguyên",
  "Xã Thanh Hòa, Tỉnh Thái Nguyên",
  "Xã Thanh Sơn, Tỉnh Thái Nguyên",
  "Xã Thanh Thành, Tỉnh Thái Nguyên",
  "Xã Thanh An, Tỉnh Thái Nguyên",
  "Xã Thanh Lộc, Tỉnh Thái Nguyên",
  "Xã Thanh Thịnh, Tỉnh Thái Nguyên",
  "Xã An Bình, Tỉnh Thái Nguyên",
  "Xã An Hòa, Tỉnh Thái Nguyên",
  "Xã An Phú, Tỉnh Thái Nguyên",
  "Xã An Lạc, Tỉnh Thái Nguyên",
  "Xã An Thịnh, Tỉnh Thái Nguyên",
  "Xã An Thành, Tỉnh Thái Nguyên",
  "Xã An Sơn, Tỉnh Thái Nguyên",
  "Xã An Khánh, Tỉnh Thái Nguyên",
  "Xã Bình An, Tỉnh Thái Nguyên",
  "Xã Bình Minh, Tỉnh Thái Nguyên",
  "Xã Bình Phú, Tỉnh Thái Nguyên",
  "Xã Bình Hòa, Tỉnh Thái Nguyên",
  "Xã Bình Thành, Tỉnh Thái Nguyên",
  "Xã Bình Sơn, Tỉnh Thái Nguyên",
  "Xã Bình Lộc, Tỉnh Thái Nguyên",
  "Xã Bình Thịnh, Tỉnh Thái Nguyên",
  "Xã Hòa Bình, Tỉnh Thái Nguyên",
  "Xã Hòa Phú, Tỉnh Thái Nguyên",
  "Xã Hòa An, Tỉnh Thái Nguyên",
  "Xã Hòa Thành, Tỉnh Thái Nguyên",
  "Xã Hòa Sơn, Tỉnh Thái Nguyên",
  "Xã Hòa Lộc, Tỉnh Thái Nguyên",
  "Xã Hòa Thịnh, Tỉnh Thái Nguyên",
  "Xã Hòa Minh, Tỉnh Thái Nguyên",
  "Xã Phú An, Tỉnh Thái Nguyên",
  "Xã Phú Bình, Tỉnh Thái Nguyên",
  "Xã Phú Hòa, Tỉnh Thái Nguyên",
  "Xã Phú Lộc, Tỉnh Thái Nguyên",
  "Xã Phú Mỹ, Tỉnh Thái Nguyên",
  "Xã Phú Sơn, Tỉnh Thái Nguyên",
  "Xã Phú Thành, Tỉnh Thái Nguyên",
  "Xã Phú Thịnh, Tỉnh Thái Nguyên",
  "Xã Tân An, Tỉnh Thái Nguyên",
  "Xã Tân Bình, Tỉnh Thái Nguyên",
  "Xã An Sơn, Tỉnh Lạng Sơn",
  "Xã An Khánh, Tỉnh Lạng Sơn",
  "Xã Bình An, Tỉnh Lạng Sơn",
  "Xã Bình Minh, Tỉnh Lạng Sơn",
  "Xã Bình Phú, Tỉnh Lạng Sơn",
  "Xã Bình Hòa, Tỉnh Lạng Sơn",
  "Xã Bình Thành, Tỉnh Lạng Sơn",
  "Xã Bình Sơn, Tỉnh Lạng Sơn",
  "Xã Bình Lộc, Tỉnh Lạng Sơn",
  "Xã Bình Thịnh, Tỉnh Lạng Sơn",
  "Xã Hòa Bình, Tỉnh Lạng Sơn",
  "Xã Hòa Phú, Tỉnh Lạng Sơn",
  "Xã Hòa An, Tỉnh Lạng Sơn",
  "Xã Hòa Thành, Tỉnh Lạng Sơn",
  "Xã Hòa Sơn, Tỉnh Lạng Sơn",
  "Xã Hòa Lộc, Tỉnh Lạng Sơn",
  "Xã Hòa Thịnh, Tỉnh Lạng Sơn",
  "Xã Hòa Minh, Tỉnh Lạng Sơn",
  "Xã Phú An, Tỉnh Lạng Sơn",
  "Xã Phú Bình, Tỉnh Lạng Sơn",
  "Xã Phú Hòa, Tỉnh Lạng Sơn",
  "Xã Phú Lộc, Tỉnh Lạng Sơn",
  "Xã Phú Mỹ, Tỉnh Lạng Sơn",
  "Xã Phú Sơn, Tỉnh Lạng Sơn",
  "Xã Phú Thành, Tỉnh Lạng Sơn",
  "Xã Phú Thịnh, Tỉnh Lạng Sơn",
  "Xã Tân An, Tỉnh Lạng Sơn",
  "Xã Tân Bình, Tỉnh Lạng Sơn",
  "Xã Tân Hòa, Tỉnh Lạng Sơn",
  "Xã Tân Phú, Tỉnh Lạng Sơn",
  "Xã Tân Lập, Tỉnh Lạng Sơn",
  "Xã Tân Thành, Tỉnh Lạng Sơn",
  "Xã Tân Tiến, Tỉnh Lạng Sơn",
  "Xã Tân Hưng, Tỉnh Lạng Sơn",
  "Xã Tân Long, Tỉnh Lạng Sơn",
  "Xã Tân Phong, Tỉnh Lạng Sơn",
  "Xã Tân Thịnh, Tỉnh Lạng Sơn",
  "Xã Tân Xuân, Tỉnh Lạng Sơn",
  "Xã Tân Sơn, Tỉnh Lạng Sơn",
  "Xã Tân Lộc, Tỉnh Lạng Sơn",
  "Xã Tân Mỹ, Tỉnh Lạng Sơn",
  "Xã Tân Minh, Tỉnh Lạng Sơn",
  "Xã Minh Tân, Tỉnh Lạng Sơn",
  "Xã Minh Phú, Tỉnh Lạng Sơn",
  "Xã Minh Hòa, Tỉnh Lạng Sơn",
  "Xã Minh Sơn, Tỉnh Lạng Sơn",
  "Xã Minh Đức, Tỉnh Lạng Sơn",
  "Xã Minh Thành, Tỉnh Lạng Sơn",
  "Xã Minh An, Tỉnh Lạng Sơn",
  "Xã Minh Lộc, Tỉnh Lạng Sơn",
  "Xã Đông Hòa, Tỉnh Lạng Sơn",
  "Xã Đông Phú, Tỉnh Lạng Sơn",
  "Xã Đông Sơn, Tỉnh Lạng Sơn",
  "Xã Đông Thành, Tỉnh Lạng Sơn",
  "Xã Đông An, Tỉnh Lạng Sơn",
  "Xã Đông Lộc, Tỉnh Lạng Sơn",
  "Xã Đông Thịnh, Tỉnh Lạng Sơn",
  "Xã Tân Phú, Tỉnh Quảng Ninh",
  "Xã Tân Lập, Tỉnh Quảng Ninh",
  "Xã Tân Thành, Tỉnh Quảng Ninh",
  "Xã Tân Tiến, Tỉnh Quảng Ninh",
  "Xã Tân Hưng, Tỉnh Quảng Ninh",
  "Xã Tân Long, Tỉnh Quảng Ninh",
  "Xã Tân Phong, Tỉnh Quảng Ninh",
  "Xã Tân Thịnh, Tỉnh Quảng Ninh",
  "Xã Tân Xuân, Tỉnh Quảng Ninh",
  "Xã Tân Sơn, Tỉnh Quảng Ninh",
  "Xã Tân Lộc, Tỉnh Quảng Ninh",
  "Xã Tân Mỹ, Tỉnh Quảng Ninh",
  "Xã Tân Minh, Tỉnh Quảng Ninh",
  "Xã Minh Tân, Tỉnh Quảng Ninh",
  "Xã Minh Phú, Tỉnh Quảng Ninh",
  "Xã Minh Hòa, Tỉnh Quảng Ninh",
  "Xã Minh Sơn, Tỉnh Quảng Ninh",
  "Xã Minh Đức, Tỉnh Quảng Ninh",
  "Xã Minh Thành, Tỉnh Quảng Ninh",
  "Xã Minh An, Tỉnh Quảng Ninh",
  "Xã Minh Lộc, Tỉnh Quảng Ninh",
  "Xã Đông Hòa, Tỉnh Quảng Ninh",
  "Xã Đông Phú, Tỉnh Quảng Ninh",
  "Xã Đông Sơn, Tỉnh Quảng Ninh",
  "Xã Đông Thành, Tỉnh Quảng Ninh",
  "Xã Đông An, Tỉnh Quảng Ninh",
  "Xã Đông Lộc, Tỉnh Quảng Ninh",
  "Xã Đông Thịnh, Tỉnh Quảng Ninh",
  "Xã Đông Minh, Tỉnh Quảng Ninh",
  "Xã Tây Sơn, Tỉnh Quảng Ninh",
  "Xã Tây Phú, Tỉnh Quảng Ninh",
  "Xã Tây Hòa, Tỉnh Quảng Ninh",
  "Xã Tây An, Tỉnh Quảng Ninh",
  "Xã Tây Thành, Tỉnh Quảng Ninh",
  "Xã Tây Lộc, Tỉnh Quảng Ninh",
  "Xã Tây Thịnh, Tỉnh Quảng Ninh",
  "Xã Tây Minh, Tỉnh Quảng Ninh",
  "Xã Nam Sơn, Tỉnh Quảng Ninh",
  "Xã Nam Phú, Tỉnh Quảng Ninh",
  "Xã Nam Hòa, Tỉnh Quảng Ninh",
  "Xã Nam An, Tỉnh Quảng Ninh",
  "Xã Nam Thành, Tỉnh Quảng Ninh",
  "Xã Nam Lộc, Tỉnh Quảng Ninh",
  "Xã Nam Thịnh, Tỉnh Quảng Ninh",
  "Xã Nam Bình, Tỉnh Quảng Ninh",
  "Xã Bắc Sơn, Tỉnh Quảng Ninh",
  "Xã Bắc Phú, Tỉnh Quảng Ninh",
  "Xã Bắc Hòa, Tỉnh Quảng Ninh",
  "Xã Bắc An, Tỉnh Quảng Ninh",
  "Xã Bắc Thành, Tỉnh Quảng Ninh",
  "Xã Bắc Lộc, Tỉnh Quảng Ninh",
  "Xã Bắc Thịnh, Tỉnh Quảng Ninh",
  "Xã Bắc Bình, Tỉnh Quảng Ninh",
  "Xã Xuân Hòa, Tỉnh Quảng Ninh",
  "Xã Xuân Phú, Tỉnh Quảng Ninh",
  "Xã Xuân Lộc, Tỉnh Quảng Ninh",
  "Xã Xuân Sơn, Tỉnh Quảng Ninh",
  "Xã Tây Sơn, Tỉnh Bắc Ninh",
  "Xã Tây Phú, Tỉnh Bắc Ninh",
  "Xã Tây Hòa, Tỉnh Bắc Ninh",
  "Xã Tây An, Tỉnh Bắc Ninh",
  "Xã Tây Thành, Tỉnh Bắc Ninh",
  "Xã Tây Lộc, Tỉnh Bắc Ninh",
  "Xã Tây Thịnh, Tỉnh Bắc Ninh",
  "Xã Tây Minh, Tỉnh Bắc Ninh",
  "Xã Nam Sơn, Tỉnh Bắc Ninh",
  "Xã Nam Phú, Tỉnh Bắc Ninh",
  "Xã Nam Hòa, Tỉnh Bắc Ninh",
  "Xã Nam An, Tỉnh Bắc Ninh",
  "Xã Nam Thành, Tỉnh Bắc Ninh",
  "Xã Nam Lộc, Tỉnh Bắc Ninh",
  "Xã Nam Thịnh, Tỉnh Bắc Ninh",
  "Xã Nam Bình, Tỉnh Bắc Ninh",
  "Xã Bắc Sơn, Tỉnh Bắc Ninh",
  "Xã Bắc Phú, Tỉnh Bắc Ninh",
  "Xã Bắc Hòa, Tỉnh Bắc Ninh",
  "Xã Bắc An, Tỉnh Bắc Ninh",
  "Xã Bắc Thành, Tỉnh Bắc Ninh",
  "Xã Bắc Lộc, Tỉnh Bắc Ninh",
  "Xã Bắc Thịnh, Tỉnh Bắc Ninh",
  "Xã Bắc Bình, Tỉnh Bắc Ninh",
  "Xã Xuân Hòa, Tỉnh Bắc Ninh",
  "Xã Xuân Phú, Tỉnh Bắc Ninh",
  "Xã Xuân Lộc, Tỉnh Bắc Ninh",
  "Xã Xuân Sơn, Tỉnh Bắc Ninh",
  "Xã Xuân Thành, Tỉnh Bắc Ninh",
  "Xã Xuân Thịnh, Tỉnh Bắc Ninh",
  "Xã Xuân An, Tỉnh Bắc Ninh",
  "Xã Xuân Bình, Tỉnh Bắc Ninh",
  "Xã Trung Sơn, Tỉnh Bắc Ninh",
  "Xã Trung Hòa, Tỉnh Bắc Ninh",
  "Xã Trung Thành, Tỉnh Bắc Ninh",
  "Xã Trung An, Tỉnh Bắc Ninh",
  "Xã Trung Phú, Tỉnh Bắc Ninh",
  "Xã Trung Lộc, Tỉnh Bắc Ninh",
  "Xã Trung Thịnh, Tỉnh Bắc Ninh",
  "Xã Trung Bình, Tỉnh Bắc Ninh",
  "Xã Đại An, Tỉnh Bắc Ninh",
  "Xã Đại Phú, Tỉnh Bắc Ninh",
  "Xã Đại Hòa, Tỉnh Bắc Ninh",
  "Xã Đại Sơn, Tỉnh Bắc Ninh",
  "Xã Đại Thành, Tỉnh Bắc Ninh",
  "Xã Đại Lộc, Tỉnh Bắc Ninh",
  "Xã Đại Bình, Tỉnh Bắc Ninh",
  "Xã Đại Minh, Tỉnh Bắc Ninh",
  "Xã Long An, Tỉnh Bắc Ninh",
  "Xã Long Bình, Tỉnh Bắc Ninh",
  "Xã Long Phú, Tỉnh Bắc Ninh",
  "Xã Long Hòa, Tỉnh Bắc Ninh",
  "Xã Long Thành, Tỉnh Bắc Ninh",
  "Xã Long Sơn, Tỉnh Bắc Ninh",
  "Xã Long Lộc, Tỉnh Bắc Ninh",
  "Xã Long Thịnh, Tỉnh Bắc Ninh",
  "Xã Thành Công, Tỉnh Bắc Ninh",
  "Xã Xuân Thịnh, Tỉnh Phú Thọ",
  "Xã Xuân An, Tỉnh Phú Thọ",
  "Xã Xuân Bình, Tỉnh Phú Thọ",
  "Xã Trung Sơn, Tỉnh Phú Thọ",
  "Xã Trung Hòa, Tỉnh Phú Thọ",
  "Xã Trung Thành, Tỉnh Phú Thọ",
  "Xã Trung An, Tỉnh Phú Thọ",
  "Xã Trung Phú, Tỉnh Phú Thọ",
  "Xã Trung Lộc, Tỉnh Phú Thọ",
  "Xã Trung Thịnh, Tỉnh Phú Thọ",
  "Xã Trung Bình, Tỉnh Phú Thọ",
  "Xã Đại An, Tỉnh Phú Thọ",
  "Xã Đại Phú, Tỉnh Phú Thọ",
  "Xã Đại Hòa, Tỉnh Phú Thọ",
  "Xã Đại Sơn, Tỉnh Phú Thọ",
  "Xã Đại Thành, Tỉnh Phú Thọ",
  "Xã Đại Lộc, Tỉnh Phú Thọ",
  "Xã Đại Bình, Tỉnh Phú Thọ",
  "Xã Đại Minh, Tỉnh Phú Thọ",
  "Xã Long An, Tỉnh Phú Thọ",
  "Xã Long Bình, Tỉnh Phú Thọ",
  "Xã Long Phú, Tỉnh Phú Thọ",
  "Xã Long Hòa, Tỉnh Phú Thọ",
  "Xã Long Thành, Tỉnh Phú Thọ",
  "Xã Long Sơn, Tỉnh Phú Thọ",
  "Xã Long Lộc, Tỉnh Phú Thọ",
  "Xã Long Thịnh, Tỉnh Phú Thọ",
  "Xã Thành Công, Tỉnh Phú Thọ",
  "Xã Thành An, Tỉnh Phú Thọ",
  "Xã Thành Bình, Tỉnh Phú Thọ",
  "Xã Thành Phú, Tỉnh Phú Thọ",
  "Xã Thành Hòa, Tỉnh Phú Thọ",
  "Xã Thành Lộc, Tỉnh Phú Thọ",
  "Xã Thành Sơn, Tỉnh Phú Thọ",
  "Xã Thành Minh, Tỉnh Phú Thọ",
  "Xã Hưng Phú, Tỉnh Phú Thọ",
  "Xã Hưng Thịnh, Tỉnh Phú Thọ",
  "Xã Hưng Hòa, Tỉnh Phú Thọ",
  "Xã Hưng Thành, Tỉnh Phú Thọ",
  "Xã Hưng An, Tỉnh Phú Thọ",
  "Xã Hưng Bình, Tỉnh Phú Thọ",
  "Xã Hưng Lộc, Tỉnh Phú Thọ",
  "Xã Hưng Sơn, Tỉnh Phú Thọ",
  "Xã Thịnh An, Tỉnh Phú Thọ",
  "Xã Thịnh Phú, Tỉnh Phú Thọ",
  "Xã Thịnh Hòa, Tỉnh Phú Thọ",
  "Xã Thịnh Thành, Tỉnh Phú Thọ",
  "Xã Thịnh Bình, Tỉnh Phú Thọ",
  "Xã Thịnh Sơn, Tỉnh Phú Thọ",
  "Xã Thịnh Lộc, Tỉnh Phú Thọ",
  "Xã Thịnh Minh, Tỉnh Phú Thọ",
  "Xã Yên Bình, Tỉnh Phú Thọ",
  "Xã Yên Phú, Tỉnh Phú Thọ",
  "Xã Yên Hòa, Tỉnh Phú Thọ",
  "Xã Yên Thành, Tỉnh Phú Thọ",
  "Xã Yên Sơn, Tỉnh Phú Thọ",
  "Xã Yên An, Tỉnh Phú Thọ",
  "Xã Thành Bình, Tỉnh Hưng Yên",
  "Xã Thành Phú, Tỉnh Hưng Yên",
  "Xã Thành Hòa, Tỉnh Hưng Yên",
  "Xã Thành Lộc, Tỉnh Hưng Yên",
  "Xã Thành Sơn, Tỉnh Hưng Yên",
  "Xã Thành Minh, Tỉnh Hưng Yên",
  "Xã Hưng Phú, Tỉnh Hưng Yên",
  "Xã Hưng Thịnh, Tỉnh Hưng Yên",
  "Xã Hưng Hòa, Tỉnh Hưng Yên",
  "Xã Hưng Thành, Tỉnh Hưng Yên",
  "Xã Hưng An, Tỉnh Hưng Yên",
  "Xã Hưng Bình, Tỉnh Hưng Yên",
  "Xã Hưng Lộc, Tỉnh Hưng Yên",
  "Xã Hưng Sơn, Tỉnh Hưng Yên",
  "Xã Thịnh An, Tỉnh Hưng Yên",
  "Xã Thịnh Phú, Tỉnh Hưng Yên",
  "Xã Thịnh Hòa, Tỉnh Hưng Yên",
  "Xã Thịnh Thành, Tỉnh Hưng Yên",
  "Xã Thịnh Bình, Tỉnh Hưng Yên",
  "Xã Thịnh Sơn, Tỉnh Hưng Yên",
  "Xã Thịnh Lộc, Tỉnh Hưng Yên",
  "Xã Thịnh Minh, Tỉnh Hưng Yên",
  "Xã Yên Bình, Tỉnh Hưng Yên",
  "Xã Yên Phú, Tỉnh Hưng Yên",
  "Xã Yên Hòa, Tỉnh Hưng Yên",
  "Xã Yên Thành, Tỉnh Hưng Yên",
  "Xã Yên Sơn, Tỉnh Hưng Yên",
  "Xã Yên An, Tỉnh Hưng Yên",
  "Xã Yên Lộc, Tỉnh Hưng Yên",
  "Xã Yên Thịnh, Tỉnh Hưng Yên",
  "Xã Quang Trung, Tỉnh Hưng Yên",
  "Xã Quang Minh, Tỉnh Hưng Yên",
  "Xã Quang Phú, Tỉnh Hưng Yên",
  "Xã Quang Hòa, Tỉnh Hưng Yên",
  "Xã Quang An, Tỉnh Hưng Yên",
  "Xã Quang Thành, Tỉnh Hưng Yên",
  "Xã Quang Sơn, Tỉnh Hưng Yên",
  "Xã Quang Lộc, Tỉnh Hưng Yên",
  "Xã Đức Hòa, Tỉnh Hưng Yên",
  "Xã Đức Phú, Tỉnh Hưng Yên",
  "Xã Đức Thành, Tỉnh Hưng Yên",
  "Xã Đức Thịnh, Tỉnh Hưng Yên",
  "Xã Đức An, Tỉnh Hưng Yên",
  "Xã Đức Bình, Tỉnh Hưng Yên",
  "Xã Đức Sơn, Tỉnh Hưng Yên",
  "Xã Đức Lộc, Tỉnh Hưng Yên",
  "Xã Vĩnh An, Tỉnh Hưng Yên",
  "Xã Vĩnh Bình, Tỉnh Hưng Yên",
  "Xã Vĩnh Phú, Tỉnh Hưng Yên",
  "Xã Vĩnh Hòa, Tỉnh Hưng Yên",
  "Xã Vĩnh Thành, Tỉnh Hưng Yên",
  "Xã Vĩnh Sơn, Tỉnh Hưng Yên",
  "Xã Vĩnh Lộc, Tỉnh Hưng Yên",
  "Xã Vĩnh Thịnh, Tỉnh Hưng Yên",
  "Xã Lộc An, Tỉnh Hưng Yên",
  "Xã Lộc Bình, Tỉnh Hưng Yên",
  "Xã Lộc Phú, Tỉnh Hưng Yên",
  "Xã Yên Thịnh, Tỉnh Ninh Bình",
  "Xã Quang Trung, Tỉnh Ninh Bình",
  "Xã Quang Minh, Tỉnh Ninh Bình",
  "Xã Quang Phú, Tỉnh Ninh Bình",
  "Xã Quang Hòa, Tỉnh Ninh Bình",
  "Xã Quang An, Tỉnh Ninh Bình",
  "Xã Quang Thành, Tỉnh Ninh Bình",
  "Xã Quang Sơn, Tỉnh Ninh Bình",
  "Xã Quang Lộc, Tỉnh Ninh Bình",
  "Xã Đức Hòa, Tỉnh Ninh Bình",
  "Xã Đức Phú, Tỉnh Ninh Bình",
  "Xã Đức Thành, Tỉnh Ninh Bình",
  "Xã Đức Thịnh, Tỉnh Ninh Bình",
  "Xã Đức An, Tỉnh Ninh Bình",
  "Xã Đức Bình, Tỉnh Ninh Bình",
  "Xã Đức Sơn, Tỉnh Ninh Bình",
  "Xã Đức Lộc, Tỉnh Ninh Bình",
  "Xã Vĩnh An, Tỉnh Ninh Bình",
  "Xã Vĩnh Bình, Tỉnh Ninh Bình",
  "Xã Vĩnh Phú, Tỉnh Ninh Bình",
  "Xã Vĩnh Hòa, Tỉnh Ninh Bình",
  "Xã Vĩnh Thành, Tỉnh Ninh Bình",
  "Xã Vĩnh Sơn, Tỉnh Ninh Bình",
  "Xã Vĩnh Lộc, Tỉnh Ninh Bình",
  "Xã Vĩnh Thịnh, Tỉnh Ninh Bình",
  "Xã Lộc An, Tỉnh Ninh Bình",
  "Xã Lộc Bình, Tỉnh Ninh Bình",
  "Xã Lộc Phú, Tỉnh Ninh Bình",
  "Xã Lộc Hòa, Tỉnh Ninh Bình",
  "Xã Lộc Thành, Tỉnh Ninh Bình",
  "Xã Lộc Sơn, Tỉnh Ninh Bình",
  "Xã Lộc Thịnh, Tỉnh Ninh Bình",
  "Xã Lộc Minh, Tỉnh Ninh Bình",
  "Xã Mỹ An, Tỉnh Ninh Bình",
  "Xã Mỹ Bình, Tỉnh Ninh Bình",
  "Xã Mỹ Phú, Tỉnh Ninh Bình",
  "Xã Mỹ Hòa, Tỉnh Ninh Bình",
  "Xã Mỹ Thành, Tỉnh Ninh Bình",
  "Xã Mỹ Sơn, Tỉnh Ninh Bình",
  "Xã Mỹ Lộc, Tỉnh Ninh Bình",
  "Xã Mỹ Thịnh, Tỉnh Ninh Bình",
  "Xã Kim Sơn, Tỉnh Ninh Bình",
  "Xã Kim Phú, Tỉnh Ninh Bình",
  "Xã Kim Thành, Tỉnh Ninh Bình",
  "Xã Kim An, Tỉnh Ninh Bình",
  "Xã Kim Bình, Tỉnh Ninh Bình",
  "Xã Kim Hòa, Tỉnh Ninh Bình",
  "Xã Kim Lộc, Tỉnh Ninh Bình",
  "Xã Kim Thịnh, Tỉnh Ninh Bình",
  "Xã Thanh Bình, Tỉnh Ninh Bình",
  "Xã Thanh Phú, Tỉnh Ninh Bình",
  "Xã Thanh Hòa, Tỉnh Ninh Bình",
  "Xã Thanh Sơn, Tỉnh Ninh Bình",
  "Xã Thanh Thành, Tỉnh Ninh Bình",
  "Xã Thanh An, Tỉnh Ninh Bình",
  "Xã Thanh Lộc, Tỉnh Ninh Bình",
  "Xã Thanh Thịnh, Tỉnh Ninh Bình",
  "Xã Lộc Thành, Tỉnh Thanh Hóa",
  "Xã Lộc Sơn, Tỉnh Thanh Hóa",
  "Xã Lộc Thịnh, Tỉnh Thanh Hóa",
  "Xã Lộc Minh, Tỉnh Thanh Hóa",
  "Xã Mỹ An, Tỉnh Thanh Hóa",
  "Xã Mỹ Bình, Tỉnh Thanh Hóa",
  "Xã Mỹ Phú, Tỉnh Thanh Hóa",
  "Xã Mỹ Hòa, Tỉnh Thanh Hóa",
  "Xã Mỹ Thành, Tỉnh Thanh Hóa",
  "Xã Mỹ Sơn, Tỉnh Thanh Hóa",
  "Xã Mỹ Lộc, Tỉnh Thanh Hóa",
  "Xã Mỹ Thịnh, Tỉnh Thanh Hóa",
  "Xã Kim Sơn, Tỉnh Thanh Hóa",
  "Xã Kim Phú, Tỉnh Thanh Hóa",
  "Xã Kim Thành, Tỉnh Thanh Hóa",
  "Xã Kim An, Tỉnh Thanh Hóa",
  "Xã Kim Bình, Tỉnh Thanh Hóa",
  "Xã Kim Hòa, Tỉnh Thanh Hóa",
  "Xã Kim Lộc, Tỉnh Thanh Hóa",
  "Xã Kim Thịnh, Tỉnh Thanh Hóa",
  "Xã Thanh Bình, Tỉnh Thanh Hóa",
  "Xã Thanh Phú, Tỉnh Thanh Hóa",
  "Xã Thanh Hòa, Tỉnh Thanh Hóa",
  "Xã Thanh Sơn, Tỉnh Thanh Hóa",
  "Xã Thanh Thành, Tỉnh Thanh Hóa",
  "Xã Thanh An, Tỉnh Thanh Hóa",
  "Xã Thanh Lộc, Tỉnh Thanh Hóa",
  "Xã Thanh Thịnh, Tỉnh Thanh Hóa",
  "Xã An Bình, Tỉnh Thanh Hóa",
  "Xã An Hòa, Tỉnh Thanh Hóa",
  "Xã An Phú, Tỉnh Thanh Hóa",
  "Xã An Lạc, Tỉnh Thanh Hóa",
  "Xã An Thịnh, Tỉnh Thanh Hóa",
  "Xã An Thành, Tỉnh Thanh Hóa",
  "Xã An Sơn, Tỉnh Thanh Hóa",
  "Xã An Khánh, Tỉnh Thanh Hóa",
  "Xã Bình An, Tỉnh Thanh Hóa",
  "Xã Bình Minh, Tỉnh Thanh Hóa",
  "Xã Bình Phú, Tỉnh Thanh Hóa",
  "Xã Bình Hòa, Tỉnh Thanh Hóa",
  "Xã Bình Thành, Tỉnh Thanh Hóa",
  "Xã Bình Sơn, Tỉnh Thanh Hóa",
  "Xã Bình Lộc, Tỉnh Thanh Hóa",
  "Xã Bình Thịnh, Tỉnh Thanh Hóa",
  "Xã Hòa Bình, Tỉnh Thanh Hóa",
  "Xã Hòa Phú, Tỉnh Thanh Hóa",
  "Xã Hòa An, Tỉnh Thanh Hóa",
  "Xã Hòa Thành, Tỉnh Thanh Hóa",
  "Xã Hòa Sơn, Tỉnh Thanh Hóa",
  "Xã Hòa Lộc, Tỉnh Thanh Hóa",
  "Xã Hòa Thịnh, Tỉnh Thanh Hóa",
  "Xã Hòa Minh, Tỉnh Thanh Hóa",
  "Xã Phú An, Tỉnh Thanh Hóa",
  "Xã Phú Bình, Tỉnh Thanh Hóa",
  "Xã Phú Hòa, Tỉnh Thanh Hóa",
  "Xã Phú Lộc, Tỉnh Thanh Hóa",
  "Xã Phú Mỹ, Tỉnh Thanh Hóa",
  "Xã An Hòa, Tỉnh Nghệ An",
  "Xã An Phú, Tỉnh Nghệ An",
  "Xã An Lạc, Tỉnh Nghệ An",
  "Xã An Thịnh, Tỉnh Nghệ An",
  "Xã An Thành, Tỉnh Nghệ An",
  "Xã An Sơn, Tỉnh Nghệ An",
  "Xã An Khánh, Tỉnh Nghệ An",
  "Xã Bình An, Tỉnh Nghệ An",
  "Xã Bình Minh, Tỉnh Nghệ An",
  "Xã Bình Phú, Tỉnh Nghệ An",
  "Xã Bình Hòa, Tỉnh Nghệ An",
  "Xã Bình Thành, Tỉnh Nghệ An",
  "Xã Bình Sơn, Tỉnh Nghệ An",
  "Xã Bình Lộc, Tỉnh Nghệ An",
  "Xã Bình Thịnh, Tỉnh Nghệ An",
  "Xã Hòa Bình, Tỉnh Nghệ An",
  "Xã Hòa Phú, Tỉnh Nghệ An",
  "Xã Hòa An, Tỉnh Nghệ An",
  "Xã Hòa Thành, Tỉnh Nghệ An",
  "Xã Hòa Sơn, Tỉnh Nghệ An",
  "Xã Hòa Lộc, Tỉnh Nghệ An",
  "Xã Hòa Thịnh, Tỉnh Nghệ An",
  "Xã Hòa Minh, Tỉnh Nghệ An",
  "Xã Phú An, Tỉnh Nghệ An",
  "Xã Phú Bình, Tỉnh Nghệ An",
  "Xã Phú Hòa, Tỉnh Nghệ An",
  "Xã Phú Lộc, Tỉnh Nghệ An",
  "Xã Phú Mỹ, Tỉnh Nghệ An",
  "Xã Phú Sơn, Tỉnh Nghệ An",
  "Xã Phú Thành, Tỉnh Nghệ An",
  "Xã Phú Thịnh, Tỉnh Nghệ An",
  "Xã Tân An, Tỉnh Nghệ An",
  "Xã Tân Bình, Tỉnh Nghệ An",
  "Xã Tân Hòa, Tỉnh Nghệ An",
  "Xã Tân Phú, Tỉnh Nghệ An",
  "Xã Tân Lập, Tỉnh Nghệ An",
  "Xã Tân Thành, Tỉnh Nghệ An",
  "Xã Tân Tiến, Tỉnh Nghệ An",
  "Xã Tân Hưng, Tỉnh Nghệ An",
  "Xã Tân Long, Tỉnh Nghệ An",
  "Xã Tân Phong, Tỉnh Nghệ An",
  "Xã Tân Thịnh, Tỉnh Nghệ An",
  "Xã Tân Xuân, Tỉnh Nghệ An",
  "Xã Tân Sơn, Tỉnh Nghệ An",
  "Xã Tân Lộc, Tỉnh Nghệ An",
  "Xã Tân Mỹ, Tỉnh Nghệ An",
  "Xã Tân Minh, Tỉnh Nghệ An",
  "Xã Minh Tân, Tỉnh Nghệ An",
  "Xã Minh Phú, Tỉnh Nghệ An",
  "Xã Minh Hòa, Tỉnh Nghệ An",
  "Xã Minh Sơn, Tỉnh Nghệ An",
  "Xã Minh Đức, Tỉnh Nghệ An",
  "Xã Minh Thành, Tỉnh Nghệ An",
  "Xã Minh An, Tỉnh Nghệ An",
  "Xã Minh Lộc, Tỉnh Nghệ An",
  "Xã Đông Hòa, Tỉnh Nghệ An",
  "Xã Đông Phú, Tỉnh Nghệ An",
  "Xã Phú Thành, Tỉnh Hà Tĩnh",
  "Xã Phú Thịnh, Tỉnh Hà Tĩnh",
  "Xã Tân An, Tỉnh Hà Tĩnh",
  "Xã Tân Bình, Tỉnh Hà Tĩnh",
  "Xã Tân Hòa, Tỉnh Hà Tĩnh",
  "Xã Tân Phú, Tỉnh Hà Tĩnh",
  "Xã Tân Lập, Tỉnh Hà Tĩnh",
  "Xã Tân Thành, Tỉnh Hà Tĩnh",
  "Xã Tân Tiến, Tỉnh Hà Tĩnh",
  "Xã Tân Hưng, Tỉnh Hà Tĩnh",
  "Xã Tân Long, Tỉnh Hà Tĩnh",
  "Xã Tân Phong, Tỉnh Hà Tĩnh",
  "Xã Tân Thịnh, Tỉnh Hà Tĩnh",
  "Xã Tân Xuân, Tỉnh Hà Tĩnh",
  "Xã Tân Sơn, Tỉnh Hà Tĩnh",
  "Xã Tân Lộc, Tỉnh Hà Tĩnh",
  "Xã Tân Mỹ, Tỉnh Hà Tĩnh",
  "Xã Tân Minh, Tỉnh Hà Tĩnh",
  "Xã Minh Tân, Tỉnh Hà Tĩnh",
  "Xã Minh Phú, Tỉnh Hà Tĩnh",
  "Xã Minh Hòa, Tỉnh Hà Tĩnh",
  "Xã Minh Sơn, Tỉnh Hà Tĩnh",
  "Xã Minh Đức, Tỉnh Hà Tĩnh",
  "Xã Minh Thành, Tỉnh Hà Tĩnh",
  "Xã Minh An, Tỉnh Hà Tĩnh",
  "Xã Minh Lộc, Tỉnh Hà Tĩnh",
  "Xã Đông Hòa, Tỉnh Hà Tĩnh",
  "Xã Đông Phú, Tỉnh Hà Tĩnh",
  "Xã Đông Sơn, Tỉnh Hà Tĩnh",
  "Xã Đông Thành, Tỉnh Hà Tĩnh",
  "Xã Đông An, Tỉnh Hà Tĩnh",
  "Xã Đông Lộc, Tỉnh Hà Tĩnh",
  "Xã Đông Thịnh, Tỉnh Hà Tĩnh",
  "Xã Đông Minh, Tỉnh Hà Tĩnh",
  "Xã Tây Sơn, Tỉnh Hà Tĩnh",
  "Xã Tây Phú, Tỉnh Hà Tĩnh",
  "Xã Tây Hòa, Tỉnh Hà Tĩnh",
  "Xã Tây An, Tỉnh Hà Tĩnh",
  "Xã Tây Thành, Tỉnh Hà Tĩnh",
  "Xã Tây Lộc, Tỉnh Hà Tĩnh",
  "Xã Tây Thịnh, Tỉnh Hà Tĩnh",
  "Xã Tây Minh, Tỉnh Hà Tĩnh",
  "Xã Nam Sơn, Tỉnh Hà Tĩnh",
  "Xã Nam Phú, Tỉnh Hà Tĩnh",
  "Xã Nam Hòa, Tỉnh Hà Tĩnh",
  "Xã Nam An, Tỉnh Hà Tĩnh",
  "Xã Nam Thành, Tỉnh Hà Tĩnh",
  "Xã Nam Lộc, Tỉnh Hà Tĩnh",
  "Xã Nam Thịnh, Tỉnh Hà Tĩnh",
  "Xã Nam Bình, Tỉnh Hà Tĩnh",
  "Xã Bắc Sơn, Tỉnh Hà Tĩnh",
  "Xã Bắc Phú, Tỉnh Hà Tĩnh",
  "Xã Bắc Hòa, Tỉnh Hà Tĩnh",
  "Xã Bắc An, Tỉnh Hà Tĩnh",
  "Xã Bắc Thành, Tỉnh Hà Tĩnh",
  "Xã Bắc Lộc, Tỉnh Hà Tĩnh",
  "Xã Bắc Thịnh, Tỉnh Hà Tĩnh",
  "Xã Đông Thành, Tỉnh Quảng Trị",
  "Xã Đông An, Tỉnh Quảng Trị",
  "Xã Đông Lộc, Tỉnh Quảng Trị",
  "Xã Đông Thịnh, Tỉnh Quảng Trị",
  "Xã Đông Minh, Tỉnh Quảng Trị",
  "Xã Tây Sơn, Tỉnh Quảng Trị",
  "Xã Tây Phú, Tỉnh Quảng Trị",
  "Xã Tây Hòa, Tỉnh Quảng Trị",
  "Xã Tây An, Tỉnh Quảng Trị",
  "Xã Tây Thành, Tỉnh Quảng Trị",
  "Xã Tây Lộc, Tỉnh Quảng Trị",
  "Xã Tây Thịnh, Tỉnh Quảng Trị",
  "Xã Tây Minh, Tỉnh Quảng Trị",
  "Xã Nam Sơn, Tỉnh Quảng Trị",
  "Xã Nam Phú, Tỉnh Quảng Trị",
  "Xã Nam Hòa, Tỉnh Quảng Trị",
  "Xã Nam An, Tỉnh Quảng Trị",
  "Xã Nam Thành, Tỉnh Quảng Trị",
  "Xã Nam Lộc, Tỉnh Quảng Trị",
  "Xã Nam Thịnh, Tỉnh Quảng Trị",
  "Xã Nam Bình, Tỉnh Quảng Trị",
  "Xã Bắc Sơn, Tỉnh Quảng Trị",
  "Xã Bắc Phú, Tỉnh Quảng Trị",
  "Xã Bắc Hòa, Tỉnh Quảng Trị",
  "Xã Bắc An, Tỉnh Quảng Trị",
  "Xã Bắc Thành, Tỉnh Quảng Trị",
  "Xã Bắc Lộc, Tỉnh Quảng Trị",
  "Xã Bắc Thịnh, Tỉnh Quảng Trị",
  "Xã Bắc Bình, Tỉnh Quảng Trị",
  "Xã Xuân Hòa, Tỉnh Quảng Trị",
  "Xã Xuân Phú, Tỉnh Quảng Trị",
  "Xã Xuân Lộc, Tỉnh Quảng Trị",
  "Xã Xuân Sơn, Tỉnh Quảng Trị",
  "Xã Xuân Thành, Tỉnh Quảng Trị",
  "Xã Xuân Thịnh, Tỉnh Quảng Trị",
  "Xã Xuân An, Tỉnh Quảng Trị",
  "Xã Xuân Bình, Tỉnh Quảng Trị",
  "Xã Trung Sơn, Tỉnh Quảng Trị",
  "Xã Trung Hòa, Tỉnh Quảng Trị",
  "Xã Trung Thành, Tỉnh Quảng Trị",
  "Xã Trung An, Tỉnh Quảng Trị",
  "Xã Trung Phú, Tỉnh Quảng Trị",
  "Xã Trung Lộc, Tỉnh Quảng Trị",
  "Xã Trung Thịnh, Tỉnh Quảng Trị",
  "Xã Trung Bình, Tỉnh Quảng Trị",
  "Xã Đại An, Tỉnh Quảng Trị",
  "Xã Đại Phú, Tỉnh Quảng Trị",
  "Xã Đại Hòa, Tỉnh Quảng Trị",
  "Xã Đại Sơn, Tỉnh Quảng Trị",
  "Xã Đại Thành, Tỉnh Quảng Trị",
  "Xã Đại Lộc, Tỉnh Quảng Trị",
  "Xã Đại Bình, Tỉnh Quảng Trị",
  "Xã Đại Minh, Tỉnh Quảng Trị",
  "Xã Long An, Tỉnh Quảng Trị",
  "Xã Long Bình, Tỉnh Quảng Trị",
  "Xã Long Phú, Tỉnh Quảng Trị",
  "Xã Long Hòa, Tỉnh Quảng Trị",
  "Xã Xuân Hòa, Tỉnh Quảng Ngãi",
  "Xã Xuân Phú, Tỉnh Quảng Ngãi",
  "Xã Xuân Lộc, Tỉnh Quảng Ngãi",
  "Xã Xuân Sơn, Tỉnh Quảng Ngãi",
  "Xã Xuân Thành, Tỉnh Quảng Ngãi",
  "Xã Xuân Thịnh, Tỉnh Quảng Ngãi",
  "Xã Xuân An, Tỉnh Quảng Ngãi",
  "Xã Xuân Bình, Tỉnh Quảng Ngãi",
  "Xã Trung Sơn, Tỉnh Quảng Ngãi",
  "Xã Trung Hòa, Tỉnh Quảng Ngãi",
  "Xã Trung Thành, Tỉnh Quảng Ngãi",
  "Xã Trung An, Tỉnh Quảng Ngãi",
  "Xã Trung Phú, Tỉnh Quảng Ngãi",
  "Xã Trung Lộc, Tỉnh Quảng Ngãi",
  "Xã Trung Thịnh, Tỉnh Quảng Ngãi",
  "Xã Trung Bình, Tỉnh Quảng Ngãi",
  "Xã Đại An, Tỉnh Quảng Ngãi",
  "Xã Đại Phú, Tỉnh Quảng Ngãi",
  "Xã Đại Hòa, Tỉnh Quảng Ngãi",
  "Xã Đại Sơn, Tỉnh Quảng Ngãi",
  "Xã Đại Thành, Tỉnh Quảng Ngãi",
  "Xã Đại Lộc, Tỉnh Quảng Ngãi",
  "Xã Đại Bình, Tỉnh Quảng Ngãi",
  "Xã Đại Minh, Tỉnh Quảng Ngãi",
  "Xã Long An, Tỉnh Quảng Ngãi",
  "Xã Long Bình, Tỉnh Quảng Ngãi",
  "Xã Long Phú, Tỉnh Quảng Ngãi",
  "Xã Long Hòa, Tỉnh Quảng Ngãi",
  "Xã Long Thành, Tỉnh Quảng Ngãi",
  "Xã Long Sơn, Tỉnh Quảng Ngãi",
  "Xã Long Lộc, Tỉnh Quảng Ngãi",
  "Xã Long Thịnh, Tỉnh Quảng Ngãi",
  "Xã Thành Công, Tỉnh Quảng Ngãi",
  "Xã Thành An, Tỉnh Quảng Ngãi",
  "Xã Thành Bình, Tỉnh Quảng Ngãi",
  "Xã Thành Phú, Tỉnh Quảng Ngãi",
  "Xã Thành Hòa, Tỉnh Quảng Ngãi",
  "Xã Thành Lộc, Tỉnh Quảng Ngãi",
  "Xã Thành Sơn, Tỉnh Quảng Ngãi",
  "Xã Thành Minh, Tỉnh Quảng Ngãi",
  "Xã Hưng Phú, Tỉnh Quảng Ngãi",
  "Xã Hưng Thịnh, Tỉnh Quảng Ngãi",
  "Xã Hưng Hòa, Tỉnh Quảng Ngãi",
  "Xã Hưng Thành, Tỉnh Quảng Ngãi",
  "Xã Hưng An, Tỉnh Quảng Ngãi",
  "Xã Hưng Bình, Tỉnh Quảng Ngãi",
  "Xã Hưng Lộc, Tỉnh Quảng Ngãi",
  "Xã Hưng Sơn, Tỉnh Quảng Ngãi",
  "Xã Thịnh An, Tỉnh Quảng Ngãi",
  "Xã Thịnh Phú, Tỉnh Quảng Ngãi",
  "Xã Thịnh Hòa, Tỉnh Quảng Ngãi",
  "Xã Thịnh Thành, Tỉnh Quảng Ngãi",
  "Xã Thịnh Bình, Tỉnh Quảng Ngãi",
  "Xã Thịnh Sơn, Tỉnh Quảng Ngãi",
  "Xã Thịnh Lộc, Tỉnh Quảng Ngãi",
  "Xã Thịnh Minh, Tỉnh Quảng Ngãi",
  "Xã Yên Bình, Tỉnh Quảng Ngãi",
  "Xã Long Sơn, Tỉnh Gia Lai",
  "Xã Long Lộc, Tỉnh Gia Lai",
  "Xã Long Thịnh, Tỉnh Gia Lai",
  "Xã Thành Công, Tỉnh Gia Lai",
  "Xã Thành An, Tỉnh Gia Lai",
  "Xã Thành Bình, Tỉnh Gia Lai",
  "Xã Thành Phú, Tỉnh Gia Lai",
  "Xã Thành Hòa, Tỉnh Gia Lai",
  "Xã Thành Lộc, Tỉnh Gia Lai",
  "Xã Thành Sơn, Tỉnh Gia Lai",
  "Xã Thành Minh, Tỉnh Gia Lai",
  "Xã Hưng Phú, Tỉnh Gia Lai",
  "Xã Hưng Thịnh, Tỉnh Gia Lai",
  "Xã Hưng Hòa, Tỉnh Gia Lai",
  "Xã Hưng Thành, Tỉnh Gia Lai",
  "Xã Hưng An, Tỉnh Gia Lai",
  "Xã Hưng Bình, Tỉnh Gia Lai",
  "Xã Hưng Lộc, Tỉnh Gia Lai",
  "Xã Hưng Sơn, Tỉnh Gia Lai",
  "Xã Thịnh An, Tỉnh Gia Lai",
  "Xã Thịnh Phú, Tỉnh Gia Lai",
  "Xã Thịnh Hòa, Tỉnh Gia Lai",
  "Xã Thịnh Thành, Tỉnh Gia Lai",
  "Xã Thịnh Bình, Tỉnh Gia Lai",
  "Xã Thịnh Sơn, Tỉnh Gia Lai",
  "Xã Thịnh Lộc, Tỉnh Gia Lai",
  "Xã Thịnh Minh, Tỉnh Gia Lai",
  "Xã Yên Bình, Tỉnh Gia Lai",
  "Xã Yên Phú, Tỉnh Gia Lai",
  "Xã Yên Hòa, Tỉnh Gia Lai",
  "Xã Yên Thành, Tỉnh Gia Lai",
  "Xã Yên Sơn, Tỉnh Gia Lai",
  "Xã Yên An, Tỉnh Gia Lai",
  "Xã Yên Lộc, Tỉnh Gia Lai",
  "Xã Yên Thịnh, Tỉnh Gia Lai",
  "Xã Quang Trung, Tỉnh Gia Lai",
  "Xã Quang Minh, Tỉnh Gia Lai",
  "Xã Quang Phú, Tỉnh Gia Lai",
  "Xã Quang Hòa, Tỉnh Gia Lai",
  "Xã Quang An, Tỉnh Gia Lai",
  "Xã Quang Thành, Tỉnh Gia Lai",
  "Xã Quang Sơn, Tỉnh Gia Lai",
  "Xã Quang Lộc, Tỉnh Gia Lai",
  "Xã Đức Hòa, Tỉnh Gia Lai",
  "Xã Đức Phú, Tỉnh Gia Lai",
  "Xã Đức Thành, Tỉnh Gia Lai",
  "Xã Đức Thịnh, Tỉnh Gia Lai",
  "Xã Đức An, Tỉnh Gia Lai",
  "Xã Đức Bình, Tỉnh Gia Lai",
  "Xã Đức Sơn, Tỉnh Gia Lai",
  "Xã Đức Lộc, Tỉnh Gia Lai",
  "Xã Vĩnh An, Tỉnh Gia Lai",
  "Xã Vĩnh Bình, Tỉnh Gia Lai",
  "Xã Vĩnh Phú, Tỉnh Gia Lai",
  "Xã Vĩnh Hòa, Tỉnh Gia Lai",
  "Xã Vĩnh Thành, Tỉnh Gia Lai",
  "Xã Vĩnh Sơn, Tỉnh Gia Lai",
  "Xã Yên Hòa, Tỉnh Khánh Hòa",
  "Xã Yên Thành, Tỉnh Khánh Hòa",
  "Xã Yên Sơn, Tỉnh Khánh Hòa",
  "Xã Yên An, Tỉnh Khánh Hòa",
  "Xã Yên Lộc, Tỉnh Khánh Hòa",
  "Xã Yên Thịnh, Tỉnh Khánh Hòa",
  "Xã Quang Trung, Tỉnh Khánh Hòa",
  "Xã Quang Minh, Tỉnh Khánh Hòa",
  "Xã Quang Phú, Tỉnh Khánh Hòa",
  "Xã Quang Hòa, Tỉnh Khánh Hòa",
  "Xã Quang An, Tỉnh Khánh Hòa",
  "Xã Quang Thành, Tỉnh Khánh Hòa",
  "Xã Quang Sơn, Tỉnh Khánh Hòa",
  "Xã Quang Lộc, Tỉnh Khánh Hòa",
  "Xã Đức Hòa, Tỉnh Khánh Hòa",
  "Xã Đức Phú, Tỉnh Khánh Hòa",
  "Xã Đức Thành, Tỉnh Khánh Hòa",
  "Xã Đức Thịnh, Tỉnh Khánh Hòa",
  "Xã Đức An, Tỉnh Khánh Hòa",
  "Xã Đức Bình, Tỉnh Khánh Hòa",
  "Xã Đức Sơn, Tỉnh Khánh Hòa",
  "Xã Đức Lộc, Tỉnh Khánh Hòa",
  "Xã Vĩnh An, Tỉnh Khánh Hòa",
  "Xã Vĩnh Bình, Tỉnh Khánh Hòa",
  "Xã Vĩnh Phú, Tỉnh Khánh Hòa",
  "Xã Vĩnh Hòa, Tỉnh Khánh Hòa",
  "Xã Vĩnh Thành, Tỉnh Khánh Hòa",
  "Xã Vĩnh Sơn, Tỉnh Khánh Hòa",
  "Xã Vĩnh Lộc, Tỉnh Khánh Hòa",
  "Xã Vĩnh Thịnh, Tỉnh Khánh Hòa",
  "Xã Lộc An, Tỉnh Khánh Hòa",
  "Xã Lộc Bình, Tỉnh Khánh Hòa",
  "Xã Lộc Phú, Tỉnh Khánh Hòa",
  "Xã Lộc Hòa, Tỉnh Khánh Hòa",
  "Xã Lộc Thành, Tỉnh Khánh Hòa",
  "Xã Lộc Sơn, Tỉnh Khánh Hòa",
  "Xã Lộc Thịnh, Tỉnh Khánh Hòa",
  "Xã Lộc Minh, Tỉnh Khánh Hòa",
  "Xã Mỹ An, Tỉnh Khánh Hòa",
  "Xã Mỹ Bình, Tỉnh Khánh Hòa",
  "Xã Mỹ Phú, Tỉnh Khánh Hòa",
  "Xã Mỹ Hòa, Tỉnh Khánh Hòa",
  "Xã Mỹ Thành, Tỉnh Khánh Hòa",
  "Xã Mỹ Sơn, Tỉnh Khánh Hòa",
  "Xã Mỹ Lộc, Tỉnh Khánh Hòa",
  "Xã Mỹ Thịnh, Tỉnh Khánh Hòa",
  "Xã Kim Sơn, Tỉnh Khánh Hòa",
  "Xã Kim Phú, Tỉnh Khánh Hòa",
  "Xã Kim Thành, Tỉnh Khánh Hòa",
  "Xã Kim An, Tỉnh Khánh Hòa",
  "Xã Kim Bình, Tỉnh Khánh Hòa",
  "Xã Kim Hòa, Tỉnh Khánh Hòa",
  "Xã Kim Lộc, Tỉnh Khánh Hòa",
  "Xã Kim Thịnh, Tỉnh Khánh Hòa",
  "Xã Thanh Bình, Tỉnh Khánh Hòa",
  "Xã Thanh Phú, Tỉnh Khánh Hòa",
  "Xã Thanh Hòa, Tỉnh Khánh Hòa",
  "Xã Vĩnh Thịnh, Tỉnh Đắk Lắk",
  "Xã Lộc An, Tỉnh Đắk Lắk",
  "Xã Lộc Bình, Tỉnh Đắk Lắk",
  "Xã Lộc Phú, Tỉnh Đắk Lắk",
  "Xã Lộc Hòa, Tỉnh Đắk Lắk",
  "Xã Lộc Thành, Tỉnh Đắk Lắk",
  "Xã Lộc Sơn, Tỉnh Đắk Lắk",
  "Xã Lộc Thịnh, Tỉnh Đắk Lắk",
  "Xã Lộc Minh, Tỉnh Đắk Lắk",
  "Xã Mỹ An, Tỉnh Đắk Lắk",
  "Xã Mỹ Bình, Tỉnh Đắk Lắk",
  "Xã Mỹ Phú, Tỉnh Đắk Lắk",
  "Xã Mỹ Hòa, Tỉnh Đắk Lắk",
  "Xã Mỹ Thành, Tỉnh Đắk Lắk",
  "Xã Mỹ Sơn, Tỉnh Đắk Lắk",
  "Xã Mỹ Lộc, Tỉnh Đắk Lắk",
  "Xã Mỹ Thịnh, Tỉnh Đắk Lắk",
  "Xã Kim Sơn, Tỉnh Đắk Lắk",
  "Xã Kim Phú, Tỉnh Đắk Lắk",
  "Xã Kim Thành, Tỉnh Đắk Lắk",
  "Xã Kim An, Tỉnh Đắk Lắk",
  "Xã Kim Bình, Tỉnh Đắk Lắk",
  "Xã Kim Hòa, Tỉnh Đắk Lắk",
  "Xã Kim Lộc, Tỉnh Đắk Lắk",
  "Xã Kim Thịnh, Tỉnh Đắk Lắk",
  "Xã Thanh Bình, Tỉnh Đắk Lắk",
  "Xã Thanh Phú, Tỉnh Đắk Lắk",
  "Xã Thanh Hòa, Tỉnh Đắk Lắk",
  "Xã Thanh Sơn, Tỉnh Đắk Lắk",
  "Xã Thanh Thành, Tỉnh Đắk Lắk",
  "Xã Thanh An, Tỉnh Đắk Lắk",
  "Xã Thanh Lộc, Tỉnh Đắk Lắk",
  "Xã Thanh Thịnh, Tỉnh Đắk Lắk",
  "Xã An Bình, Tỉnh Đắk Lắk",
  "Xã An Hòa, Tỉnh Đắk Lắk",
  "Xã An Phú, Tỉnh Đắk Lắk",
  "Xã An Lạc, Tỉnh Đắk Lắk",
  "Xã An Thịnh, Tỉnh Đắk Lắk",
  "Xã An Thành, Tỉnh Đắk Lắk",
  "Xã An Sơn, Tỉnh Đắk Lắk",
  "Xã An Khánh, Tỉnh Đắk Lắk",
  "Xã Bình An, Tỉnh Đắk Lắk",
  "Xã Bình Minh, Tỉnh Đắk Lắk",
  "Xã Bình Phú, Tỉnh Đắk Lắk",
  "Xã Bình Hòa, Tỉnh Đắk Lắk",
  "Xã Bình Thành, Tỉnh Đắk Lắk",
  "Xã Bình Sơn, Tỉnh Đắk Lắk",
  "Xã Bình Lộc, Tỉnh Đắk Lắk",
  "Xã Bình Thịnh, Tỉnh Đắk Lắk",
  "Xã Hòa Bình, Tỉnh Đắk Lắk",
  "Xã Hòa Phú, Tỉnh Đắk Lắk",
  "Xã Hòa An, Tỉnh Đắk Lắk",
  "Xã Hòa Thành, Tỉnh Đắk Lắk",
  "Xã Hòa Sơn, Tỉnh Đắk Lắk",
  "Xã Hòa Lộc, Tỉnh Đắk Lắk",
  "Xã Hòa Thịnh, Tỉnh Đắk Lắk",
  "Xã Hòa Minh, Tỉnh Đắk Lắk",
  "Xã Thanh Thành, Tỉnh Lâm Đồng",
  "Xã Thanh An, Tỉnh Lâm Đồng",
  "Xã Thanh Lộc, Tỉnh Lâm Đồng",
  "Xã Thanh Thịnh, Tỉnh Lâm Đồng",
  "Xã An Bình, Tỉnh Lâm Đồng",
  "Xã An Hòa, Tỉnh Lâm Đồng",
  "Xã An Phú, Tỉnh Lâm Đồng",
  "Xã An Lạc, Tỉnh Lâm Đồng",
  "Xã An Thịnh, Tỉnh Lâm Đồng",
  "Xã An Thành, Tỉnh Lâm Đồng",
  "Xã An Sơn, Tỉnh Lâm Đồng",
  "Xã An Khánh, Tỉnh Lâm Đồng",
  "Xã Bình An, Tỉnh Lâm Đồng",
  "Xã Bình Minh, Tỉnh Lâm Đồng",
  "Xã Bình Phú, Tỉnh Lâm Đồng",
  "Xã Bình Hòa, Tỉnh Lâm Đồng",
  "Xã Bình Thành, Tỉnh Lâm Đồng",
  "Xã Bình Sơn, Tỉnh Lâm Đồng",
  "Xã Bình Lộc, Tỉnh Lâm Đồng",
  "Xã Bình Thịnh, Tỉnh Lâm Đồng",
  "Xã Hòa Bình, Tỉnh Lâm Đồng",
  "Xã Hòa Phú, Tỉnh Lâm Đồng",
  "Xã Hòa An, Tỉnh Lâm Đồng",
  "Xã Hòa Thành, Tỉnh Lâm Đồng",
  "Xã Hòa Sơn, Tỉnh Lâm Đồng",
  "Xã Hòa Lộc, Tỉnh Lâm Đồng",
  "Xã Hòa Thịnh, Tỉnh Lâm Đồng",
  "Xã Hòa Minh, Tỉnh Lâm Đồng",
  "Xã Phú An, Tỉnh Lâm Đồng",
  "Xã Phú Bình, Tỉnh Lâm Đồng",
  "Xã Phú Hòa, Tỉnh Lâm Đồng",
  "Xã Phú Lộc, Tỉnh Lâm Đồng",
  "Xã Phú Mỹ, Tỉnh Lâm Đồng",
  "Xã Phú Sơn, Tỉnh Lâm Đồng",
  "Xã Phú Thành, Tỉnh Lâm Đồng",
  "Xã Phú Thịnh, Tỉnh Lâm Đồng",
  "Xã Tân An, Tỉnh Lâm Đồng",
  "Xã Tân Bình, Tỉnh Lâm Đồng",
  "Xã Tân Hòa, Tỉnh Lâm Đồng",
  "Xã Tân Phú, Tỉnh Lâm Đồng",
  "Xã Tân Lập, Tỉnh Lâm Đồng",
  "Xã Tân Thành, Tỉnh Lâm Đồng",
  "Xã Tân Tiến, Tỉnh Lâm Đồng",
  "Xã Tân Hưng, Tỉnh Lâm Đồng",
  "Xã Tân Long, Tỉnh Lâm Đồng",
  "Xã Tân Phong, Tỉnh Lâm Đồng",
  "Xã Tân Thịnh, Tỉnh Lâm Đồng",
  "Xã Tân Xuân, Tỉnh Lâm Đồng",
  "Xã Tân Sơn, Tỉnh Lâm Đồng",
  "Xã Tân Lộc, Tỉnh Lâm Đồng",
  "Xã Tân Mỹ, Tỉnh Lâm Đồng",
  "Xã Tân Minh, Tỉnh Lâm Đồng",
  "Xã Minh Tân, Tỉnh Lâm Đồng",
  "Xã Minh Phú, Tỉnh Lâm Đồng",
  "Xã Minh Hòa, Tỉnh Lâm Đồng",
  "Xã Minh Sơn, Tỉnh Lâm Đồng",
  "Xã Minh Đức, Tỉnh Lâm Đồng",
  "Xã Phú Bình, Tỉnh Đồng Nai",
  "Xã Phú Hòa, Tỉnh Đồng Nai",
  "Xã Phú Lộc, Tỉnh Đồng Nai",
  "Xã Phú Mỹ, Tỉnh Đồng Nai",
  "Xã Phú Sơn, Tỉnh Đồng Nai",
  "Xã Phú Thành, Tỉnh Đồng Nai",
  "Xã Phú Thịnh, Tỉnh Đồng Nai",
  "Xã Tân An, Tỉnh Đồng Nai",
  "Xã Tân Bình, Tỉnh Đồng Nai",
  "Xã Tân Hòa, Tỉnh Đồng Nai",
  "Xã Tân Phú, Tỉnh Đồng Nai",
  "Xã Tân Lập, Tỉnh Đồng Nai",
  "Xã Tân Thành, Tỉnh Đồng Nai",
  "Xã Tân Tiến, Tỉnh Đồng Nai",
  "Xã Tân Hưng, Tỉnh Đồng Nai",
  "Xã Tân Long, Tỉnh Đồng Nai",
  "Xã Tân Phong, Tỉnh Đồng Nai",
  "Xã Tân Thịnh, Tỉnh Đồng Nai",
  "Xã Tân Xuân, Tỉnh Đồng Nai",
  "Xã Tân Sơn, Tỉnh Đồng Nai",
  "Xã Tân Lộc, Tỉnh Đồng Nai",
  "Xã Tân Mỹ, Tỉnh Đồng Nai",
  "Xã Tân Minh, Tỉnh Đồng Nai",
  "Xã Minh Tân, Tỉnh Đồng Nai",
  "Xã Minh Phú, Tỉnh Đồng Nai",
  "Xã Minh Hòa, Tỉnh Đồng Nai",
  "Xã Minh Sơn, Tỉnh Đồng Nai",
  "Xã Minh Đức, Tỉnh Đồng Nai",
  "Xã Minh Thành, Tỉnh Đồng Nai",
  "Xã Minh An, Tỉnh Đồng Nai",
  "Xã Minh Lộc, Tỉnh Đồng Nai",
  "Xã Đông Hòa, Tỉnh Đồng Nai",
  "Xã Đông Phú, Tỉnh Đồng Nai",
  "Xã Đông Sơn, Tỉnh Đồng Nai",
  "Xã Đông Thành, Tỉnh Đồng Nai",
  "Xã Đông An, Tỉnh Đồng Nai",
  "Xã Đông Lộc, Tỉnh Đồng Nai",
  "Xã Đông Thịnh, Tỉnh Đồng Nai",
  "Xã Đông Minh, Tỉnh Đồng Nai",
  "Xã Tây Sơn, Tỉnh Đồng Nai",
  "Xã Tây Phú, Tỉnh Đồng Nai",
  "Xã Tây Hòa, Tỉnh Đồng Nai",
  "Xã Tây An, Tỉnh Đồng Nai",
  "Xã Tây Thành, Tỉnh Đồng Nai",
  "Xã Tây Lộc, Tỉnh Đồng Nai",
  "Xã Tây Thịnh, Tỉnh Đồng Nai",
  "Xã Tây Minh, Tỉnh Đồng Nai",
  "Xã Nam Sơn, Tỉnh Đồng Nai",
  "Xã Nam Phú, Tỉnh Đồng Nai",
  "Xã Nam Hòa, Tỉnh Đồng Nai",
  "Xã Nam An, Tỉnh Đồng Nai",
  "Xã Nam Thành, Tỉnh Đồng Nai",
  "Xã Nam Lộc, Tỉnh Đồng Nai",
  "Xã Nam Thịnh, Tỉnh Đồng Nai",
  "Xã Nam Bình, Tỉnh Đồng Nai",
  "Xã Bắc Sơn, Tỉnh Đồng Nai",
  "Xã Minh An, Tỉnh Tây Ninh",
  "Xã Minh Lộc, Tỉnh Tây Ninh",
  "Xã Đông Hòa, Tỉnh Tây Ninh",
  "Xã Đông Phú, Tỉnh Tây Ninh",
  "Xã Đông Sơn, Tỉnh Tây Ninh",
  "Xã Đông Thành, Tỉnh Tây Ninh",
  "Xã Đông An, Tỉnh Tây Ninh",
  "Xã Đông Lộc, Tỉnh Tây Ninh",
  "Xã Đông Thịnh, Tỉnh Tây Ninh",
  "Xã Đông Minh, Tỉnh Tây Ninh",
  "Xã Tây Sơn, Tỉnh Tây Ninh",
  "Xã Tây Phú, Tỉnh Tây Ninh",
  "Xã Tây Hòa, Tỉnh Tây Ninh",
  "Xã Tây An, Tỉnh Tây Ninh",
  "Xã Tây Thành, Tỉnh Tây Ninh",
  "Xã Tây Lộc, Tỉnh Tây Ninh",
  "Xã Tây Thịnh, Tỉnh Tây Ninh",
  "Xã Tây Minh, Tỉnh Tây Ninh",
  "Xã Nam Sơn, Tỉnh Tây Ninh",
  "Xã Nam Phú, Tỉnh Tây Ninh",
  "Xã Nam Hòa, Tỉnh Tây Ninh",
  "Xã Nam An, Tỉnh Tây Ninh",
  "Xã Nam Thành, Tỉnh Tây Ninh",
  "Xã Nam Lộc, Tỉnh Tây Ninh",
  "Xã Nam Thịnh, Tỉnh Tây Ninh",
  "Xã Nam Bình, Tỉnh Tây Ninh",
  "Xã Bắc Sơn, Tỉnh Tây Ninh",
  "Xã Bắc Phú, Tỉnh Tây Ninh",
  "Xã Bắc Hòa, Tỉnh Tây Ninh",
  "Xã Bắc An, Tỉnh Tây Ninh",
  "Xã Bắc Thành, Tỉnh Tây Ninh",
  "Xã Bắc Lộc, Tỉnh Tây Ninh",
  "Xã Bắc Thịnh, Tỉnh Tây Ninh",
  "Xã Bắc Bình, Tỉnh Tây Ninh",
  "Xã Xuân Hòa, Tỉnh Tây Ninh",
  "Xã Xuân Phú, Tỉnh Tây Ninh",
  "Xã Xuân Lộc, Tỉnh Tây Ninh",
  "Xã Xuân Sơn, Tỉnh Tây Ninh",
  "Xã Xuân Thành, Tỉnh Tây Ninh",
  "Xã Xuân Thịnh, Tỉnh Tây Ninh",
  "Xã Xuân An, Tỉnh Tây Ninh",
  "Xã Xuân Bình, Tỉnh Tây Ninh",
  "Xã Trung Sơn, Tỉnh Tây Ninh",
  "Xã Trung Hòa, Tỉnh Tây Ninh",
  "Xã Trung Thành, Tỉnh Tây Ninh",
  "Xã Trung An, Tỉnh Tây Ninh",
  "Xã Trung Phú, Tỉnh Tây Ninh",
  "Xã Trung Lộc, Tỉnh Tây Ninh",
  "Xã Trung Thịnh, Tỉnh Tây Ninh",
  "Xã Trung Bình, Tỉnh Tây Ninh",
  "Xã Đại An, Tỉnh Tây Ninh",
  "Xã Đại Phú, Tỉnh Tây Ninh",
  "Xã Đại Hòa, Tỉnh Tây Ninh",
  "Xã Đại Sơn, Tỉnh Tây Ninh",
  "Xã Đại Thành, Tỉnh Tây Ninh",
  "Xã Đại Lộc, Tỉnh Tây Ninh",
  "Xã Bắc An, Tỉnh Đồng Tháp",
  "Xã Bắc Thành, Tỉnh Đồng Tháp",
  "Xã Bắc Lộc, Tỉnh Đồng Tháp",
  "Xã Bắc Thịnh, Tỉnh Đồng Tháp",
  "Xã Bắc Bình, Tỉnh Đồng Tháp",
  "Xã Xuân Hòa, Tỉnh Đồng Tháp",
  "Xã Xuân Phú, Tỉnh Đồng Tháp",
  "Xã Xuân Lộc, Tỉnh Đồng Tháp",
  "Xã Xuân Sơn, Tỉnh Đồng Tháp",
  "Xã Xuân Thành, Tỉnh Đồng Tháp",
  "Xã Xuân Thịnh, Tỉnh Đồng Tháp",
  "Xã Xuân An, Tỉnh Đồng Tháp",
  "Xã Xuân Bình, Tỉnh Đồng Tháp",
  "Xã Trung Sơn, Tỉnh Đồng Tháp",
  "Xã Trung Hòa, Tỉnh Đồng Tháp",
  "Xã Trung Thành, Tỉnh Đồng Tháp",
  "Xã Trung An, Tỉnh Đồng Tháp",
  "Xã Trung Phú, Tỉnh Đồng Tháp",
  "Xã Trung Lộc, Tỉnh Đồng Tháp",
  "Xã Trung Thịnh, Tỉnh Đồng Tháp",
  "Xã Trung Bình, Tỉnh Đồng Tháp",
  "Xã Đại An, Tỉnh Đồng Tháp",
  "Xã Đại Phú, Tỉnh Đồng Tháp",
  "Xã Đại Hòa, Tỉnh Đồng Tháp",
  "Xã Đại Sơn, Tỉnh Đồng Tháp",
  "Xã Đại Thành, Tỉnh Đồng Tháp",
  "Xã Đại Lộc, Tỉnh Đồng Tháp",
  "Xã Đại Bình, Tỉnh Đồng Tháp",
  "Xã Đại Minh, Tỉnh Đồng Tháp",
  "Xã Long An, Tỉnh Đồng Tháp",
  "Xã Long Bình, Tỉnh Đồng Tháp",
  "Xã Long Phú, Tỉnh Đồng Tháp",
  "Xã Long Hòa, Tỉnh Đồng Tháp",
  "Xã Long Thành, Tỉnh Đồng Tháp",
  "Xã Long Sơn, Tỉnh Đồng Tháp",
  "Xã Long Lộc, Tỉnh Đồng Tháp",
  "Xã Long Thịnh, Tỉnh Đồng Tháp",
  "Xã Thành Công, Tỉnh Đồng Tháp",
  "Xã Thành An, Tỉnh Đồng Tháp",
  "Xã Thành Bình, Tỉnh Đồng Tháp",
  "Xã Thành Phú, Tỉnh Đồng Tháp",
  "Xã Thành Hòa, Tỉnh Đồng Tháp",
  "Xã Thành Lộc, Tỉnh Đồng Tháp",
  "Xã Thành Sơn, Tỉnh Đồng Tháp",
  "Xã Thành Minh, Tỉnh Đồng Tháp",
  "Xã Hưng Phú, Tỉnh Đồng Tháp",
  "Xã Hưng Thịnh, Tỉnh Đồng Tháp",
  "Xã Hưng Hòa, Tỉnh Đồng Tháp",
  "Xã Hưng Thành, Tỉnh Đồng Tháp",
  "Xã Hưng An, Tỉnh Đồng Tháp",
  "Xã Hưng Bình, Tỉnh Đồng Tháp",
  "Xã Hưng Lộc, Tỉnh Đồng Tháp",
  "Xã Hưng Sơn, Tỉnh Đồng Tháp",
  "Xã Thịnh An, Tỉnh Đồng Tháp",
  "Xã Thịnh Phú, Tỉnh Đồng Tháp",
  "Xã Thịnh Hòa, Tỉnh Đồng Tháp",
  "Xã Long An, Tỉnh Vĩnh Long",
  "Xã Long Bình, Tỉnh Vĩnh Long",
  "Xã Long Phú, Tỉnh Vĩnh Long",
  "Xã Long Hòa, Tỉnh Vĩnh Long",
  "Xã Long Thành, Tỉnh Vĩnh Long",
  "Xã Long Sơn, Tỉnh Vĩnh Long",
  "Xã Long Lộc, Tỉnh Vĩnh Long",
  "Xã Long Thịnh, Tỉnh Vĩnh Long",
  "Xã Thành Công, Tỉnh Vĩnh Long",
  "Xã Thành An, Tỉnh Vĩnh Long",
  "Xã Thành Bình, Tỉnh Vĩnh Long",
  "Xã Thành Phú, Tỉnh Vĩnh Long",
  "Xã Thành Hòa, Tỉnh Vĩnh Long",
  "Xã Thành Lộc, Tỉnh Vĩnh Long",
  "Xã Thành Sơn, Tỉnh Vĩnh Long",
  "Xã Thành Minh, Tỉnh Vĩnh Long",
  "Xã Hưng Phú, Tỉnh Vĩnh Long",
  "Xã Hưng Thịnh, Tỉnh Vĩnh Long",
  "Xã Hưng Hòa, Tỉnh Vĩnh Long",
  "Xã Hưng Thành, Tỉnh Vĩnh Long",
  "Xã Hưng An, Tỉnh Vĩnh Long",
  "Xã Hưng Bình, Tỉnh Vĩnh Long",
  "Xã Hưng Lộc, Tỉnh Vĩnh Long",
  "Xã Hưng Sơn, Tỉnh Vĩnh Long",
  "Xã Thịnh An, Tỉnh Vĩnh Long",
  "Xã Thịnh Phú, Tỉnh Vĩnh Long",
  "Xã Thịnh Hòa, Tỉnh Vĩnh Long",
  "Xã Thịnh Thành, Tỉnh Vĩnh Long",
  "Xã Thịnh Bình, Tỉnh Vĩnh Long",
  "Xã Thịnh Sơn, Tỉnh Vĩnh Long",
  "Xã Thịnh Lộc, Tỉnh Vĩnh Long",
  "Xã Thịnh Minh, Tỉnh Vĩnh Long",
  "Xã Yên Bình, Tỉnh Vĩnh Long",
  "Xã Yên Phú, Tỉnh Vĩnh Long",
  "Xã Yên Hòa, Tỉnh Vĩnh Long",
  "Xã Yên Thành, Tỉnh Vĩnh Long",
  "Xã Yên Sơn, Tỉnh Vĩnh Long",
  "Xã Yên An, Tỉnh Vĩnh Long",
  "Xã Yên Lộc, Tỉnh Vĩnh Long",
  "Xã Yên Thịnh, Tỉnh Vĩnh Long",
  "Xã Quang Trung, Tỉnh Vĩnh Long",
  "Xã Quang Minh, Tỉnh Vĩnh Long",
  "Xã Quang Phú, Tỉnh Vĩnh Long",
  "Xã Quang Hòa, Tỉnh Vĩnh Long",
  "Xã Quang An, Tỉnh Vĩnh Long",
  "Xã Quang Thành, Tỉnh Vĩnh Long",
  "Xã Quang Sơn, Tỉnh Vĩnh Long",
  "Xã Quang Lộc, Tỉnh Vĩnh Long",
  "Xã Đức Hòa, Tỉnh Vĩnh Long",
  "Xã Đức Phú, Tỉnh Vĩnh Long",
  "Xã Đức Thành, Tỉnh Vĩnh Long",
  "Xã Đức Thịnh, Tỉnh Vĩnh Long",
  "Xã Đức An, Tỉnh Vĩnh Long",
  "Xã Đức Bình, Tỉnh Vĩnh Long",
  "Xã Đức Sơn, Tỉnh Vĩnh Long",
  "Xã Đức Lộc, Tỉnh Vĩnh Long",
  "Xã Thịnh Sơn, Tỉnh An Giang",
  "Xã Thịnh Lộc, Tỉnh An Giang",
  "Xã Thịnh Minh, Tỉnh An Giang",
  "Xã Yên Bình, Tỉnh An Giang",
  "Xã Yên Phú, Tỉnh An Giang",
  "Xã Yên Hòa, Tỉnh An Giang",
  "Xã Yên Thành, Tỉnh An Giang",
  "Xã Yên Sơn, Tỉnh An Giang",
  "Xã Yên An, Tỉnh An Giang",
  "Xã Yên Lộc, Tỉnh An Giang",
  "Xã Yên Thịnh, Tỉnh An Giang",
  "Xã Quang Trung, Tỉnh An Giang",
  "Xã Quang Minh, Tỉnh An Giang",
  "Xã Quang Phú, Tỉnh An Giang",
  "Xã Quang Hòa, Tỉnh An Giang",
  "Xã Quang An, Tỉnh An Giang",
  "Xã Quang Thành, Tỉnh An Giang",
  "Xã Quang Sơn, Tỉnh An Giang",
  "Xã Quang Lộc, Tỉnh An Giang",
  "Xã Đức Hòa, Tỉnh An Giang",
  "Xã Đức Phú, Tỉnh An Giang",
  "Xã Đức Thành, Tỉnh An Giang",
  "Xã Đức Thịnh, Tỉnh An Giang",
  "Xã Đức An, Tỉnh An Giang",
  "Xã Đức Bình, Tỉnh An Giang",
  "Xã Đức Sơn, Tỉnh An Giang",
  "Xã Đức Lộc, Tỉnh An Giang",
  "Xã Vĩnh An, Tỉnh An Giang",
  "Xã Vĩnh Bình, Tỉnh An Giang",
  "Xã Vĩnh Phú, Tỉnh An Giang",
  "Xã Vĩnh Hòa, Tỉnh An Giang",
  "Xã Vĩnh Thành, Tỉnh An Giang",
  "Xã Vĩnh Sơn, Tỉnh An Giang",
  "Xã Vĩnh Lộc, Tỉnh An Giang",
  "Xã Vĩnh Thịnh, Tỉnh An Giang",
  "Xã Lộc An, Tỉnh An Giang",
  "Xã Lộc Bình, Tỉnh An Giang",
  "Xã Lộc Phú, Tỉnh An Giang",
  "Xã Lộc Hòa, Tỉnh An Giang",
  "Xã Lộc Thành, Tỉnh An Giang",
  "Xã Lộc Sơn, Tỉnh An Giang",
  "Xã Lộc Thịnh, Tỉnh An Giang",
  "Xã Lộc Minh, Tỉnh An Giang",
  "Xã Mỹ An, Tỉnh An Giang",
  "Xã Mỹ Bình, Tỉnh An Giang",
  "Xã Mỹ Phú, Tỉnh An Giang",
  "Xã Mỹ Hòa, Tỉnh An Giang",
  "Xã Mỹ Thành, Tỉnh An Giang",
  "Xã Mỹ Sơn, Tỉnh An Giang",
  "Xã Mỹ Lộc, Tỉnh An Giang",
  "Xã Mỹ Thịnh, Tỉnh An Giang",
  "Xã Kim Sơn, Tỉnh An Giang",
  "Xã Kim Phú, Tỉnh An Giang",
  "Xã Kim Thành, Tỉnh An Giang",
  "Xã Kim An, Tỉnh An Giang",
  "Xã Kim Bình, Tỉnh An Giang",
  "Xã Vĩnh Phú, Tỉnh Cà Mau",
  "Xã Vĩnh Hòa, Tỉnh Cà Mau",
  "Xã Vĩnh Thành, Tỉnh Cà Mau",
  "Xã Vĩnh Sơn, Tỉnh Cà Mau",
  "Xã Vĩnh Lộc, Tỉnh Cà Mau",
  "Xã Vĩnh Thịnh, Tỉnh Cà Mau",
  "Xã Lộc An, Tỉnh Cà Mau",
  "Xã Lộc Bình, Tỉnh Cà Mau",
  "Xã Lộc Phú, Tỉnh Cà Mau",
  "Xã Lộc Hòa, Tỉnh Cà Mau",
  "Xã Lộc Thành, Tỉnh Cà Mau",
  "Xã Lộc Sơn, Tỉnh Cà Mau",
  "Xã Lộc Thịnh, Tỉnh Cà Mau",
  "Xã Lộc Minh, Tỉnh Cà Mau",
  "Xã Mỹ An, Tỉnh Cà Mau",
  "Xã Mỹ Bình, Tỉnh Cà Mau",
  "Xã Mỹ Phú, Tỉnh Cà Mau",
  "Xã Mỹ Hòa, Tỉnh Cà Mau",
  "Xã Mỹ Thành, Tỉnh Cà Mau",
  "Xã Mỹ Sơn, Tỉnh Cà Mau",
  "Xã Mỹ Lộc, Tỉnh Cà Mau",
  "Xã Mỹ Thịnh, Tỉnh Cà Mau",
  "Xã Kim Sơn, Tỉnh Cà Mau",
  "Xã Kim Phú, Tỉnh Cà Mau",
  "Xã Kim Thành, Tỉnh Cà Mau",
  "Xã Kim An, Tỉnh Cà Mau",
  "Xã Kim Bình, Tỉnh Cà Mau",
  "Xã Kim Hòa, Tỉnh Cà Mau",
  "Xã Kim Lộc, Tỉnh Cà Mau",
  "Xã Kim Thịnh, Tỉnh Cà Mau",
  "Xã Thanh Bình, Tỉnh Cà Mau",
  "Xã Thanh Phú, Tỉnh Cà Mau",
  "Xã Thanh Hòa, Tỉnh Cà Mau",
  "Xã Thanh Sơn, Tỉnh Cà Mau",
  "Xã Thanh Thành, Tỉnh Cà Mau",
  "Xã Thanh An, Tỉnh Cà Mau",
  "Xã Thanh Lộc, Tỉnh Cà Mau",
  "Xã Thanh Thịnh, Tỉnh Cà Mau",
  "Xã An Bình, Tỉnh Cà Mau",
  "Xã An Hòa, Tỉnh Cà Mau",
  "Xã An Phú, Tỉnh Cà Mau",
  "Xã An Lạc, Tỉnh Cà Mau",
  "Xã An Thịnh, Tỉnh Cà Mau",
  "Xã An Thành, Tỉnh Cà Mau",
  "Xã An Sơn, Tỉnh Cà Mau",
  "Xã An Khánh, Tỉnh Cà Mau",
  "Xã Bình An, Tỉnh Cà Mau",
  "Xã Bình Minh, Tỉnh Cà Mau",
  "Xã Bình Phú, Tỉnh Cà Mau",
  "Xã Bình Hòa, Tỉnh Cà Mau",
  "Xã Bình Thành, Tỉnh Cà Mau",
  "Xã Bình Sơn, Tỉnh Cà Mau",
  "Xã Bình Lộc, Tỉnh Cà Mau",
  "Xã Bình Thịnh, Tỉnh Cà Mau",
  "Xã Hòa Bình, Tỉnh Cà Mau",
  "Xã Hòa Phú, Tỉnh Cà Mau"
] as const;

function validateSeedData(): void {
  if (TENANT_ADDRESSES.length !== EXPECTED_COUNT) {
    throw new Error(
      `Số lượng địa chỉ không hợp lệ: ${TENANT_ADDRESSES.length}. ` +
        `Cần đúng ${EXPECTED_COUNT} địa chỉ cho ID ${START_ID}-${END_ID}.`
    );
  }

  const uniqueAddresses = new Set(TENANT_ADDRESSES);
  if (uniqueAddresses.size !== TENANT_ADDRESSES.length) {
    throw new Error("Danh sách địa chỉ có dữ liệu trùng lặp.");
  }

  const hasHoChiMinh = TENANT_ADDRESSES.some(
    (address) =>
      address.includes("Hồ Chí Minh") ||
      address.toUpperCase().includes("TP.HCM")
  );

  if (hasHoChiMinh) {
    throw new Error("Danh sách địa chỉ có chứa địa chỉ thuộc TP.HCM.");
  }
}

async function validateTenantIds(): Promise<void> {
  const tenants = await prisma.tenant.findMany({
    where: {
      id: {
        gte: START_ID,
        lte: END_ID,
      },
    },
    select: {
      id: true,
    },
    orderBy: {
      id: "asc",
    },
  });

  if (tenants.length !== EXPECTED_COUNT) {
    const existingIds = new Set(tenants.map((tenant) => tenant.id));
    const missingIds: number[] = [];

    for (let id = START_ID; id <= END_ID; id++) {
      if (!existingIds.has(id)) {
        missingIds.push(id);
      }
    }

    const preview = missingIds.slice(0, 30).join(", ");
    const suffix =
      missingIds.length > 30
        ? ` ... và ${missingIds.length - 30} ID khác`
        : "";

    throw new Error(
      `Không đủ Tenant trong khoảng ID ${START_ID}-${END_ID}. ` +
        `Tìm thấy ${tenants.length}/${EXPECTED_COUNT}. ` +
        `ID bị thiếu: ${preview || "không xác định"}${suffix}.\n` +
        "Seed đã dừng trước khi cập nhật dữ liệu."
    );
  }

  // Không chỉ kiểm tra count: đảm bảo mọi ID trong khoảng đều tồn tại.
  for (let index = 0; index < tenants.length; index++) {
    const expectedId = START_ID + index;

    if (tenants[index].id !== expectedId) {
      throw new Error(
        `Tenant ID không liên tục. Mong đợi ID ${expectedId} ` +
          `nhưng nhận được ID ${tenants[index].id}.`
      );
    }
  }
}

async function updateTenantAddresses(): Promise<void> {
  for (let batchStartId = START_ID; batchStartId <= END_ID; batchStartId += BATCH_SIZE) {
    const batchEndId = Math.min(batchStartId + BATCH_SIZE - 1, END_ID);

    const updates = [];

    for (let id = batchStartId; id <= batchEndId; id++) {
      const addressIndex = id - START_ID;
      const address = TENANT_ADDRESSES[addressIndex];

      updates.push(
        prisma.tenant.update({
          where: { id },
          data: { address: address },
          select: { id: true },
        })
      );
    }

    await prisma.$transaction(updates);

    console.log(
      `✓ Đã cập nhật Tenant ID ${batchStartId}-${batchEndId} ` +
        `(${batchEndId - START_ID + 1}/${EXPECTED_COUNT})`
    );
  }
}

async function main(): Promise<void> {
  console.log(
    `Bắt đầu cập nhật địa chỉ cho Tenant ID ${START_ID}-${END_ID}...`
  );

  validateSeedData();
  await validateTenantIds();

  console.log(
    `✓ Đã kiểm tra đủ ${EXPECTED_COUNT} Tenant và ${TENANT_ADDRESSES.length} địa chỉ.`
  );

  await updateTenantAddresses();

  console.log(
    `\n✓ Hoàn tất: đã cập nhật cột address cho ${EXPECTED_COUNT} Tenant.`
  );
}

main()
  .catch((error) => {
    console.error("\n✗ Seed cập nhật địa chỉ thất bại:");
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });